import Testing

@testable import WireGenCore

@Suite("CodeEmission")
struct CodeEmissionTests {
    private func singleton(
        _ name: String,
        qualifiedTypeName: String? = nil,
        dependencies: [(name: String?, type: String)] = []
    ) -> DiscoveredBinding {
        let deps = dependencies.map {
            DependencyParameter(
                name: $0.name,
                type: $0.type,
                kind: .injectInitParameter,
                location: mockLocation("\(name).swift")
            )
        }
        return .scopeBound(
            DiscoveredScopeBoundType(
                typeName: name,
                qualifiedTypeName: qualifiedTypeName,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: deps,
                location: mockLocation("\(name).swift")
            )
        )
    }

    private func providerProperty(
        _ accessPath: String,
        boundType: String
    ) -> DiscoveredBinding {
        .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("\(accessPath).swift")
            )
        )
    }

    private func providerFunction(
        _ accessPath: String,
        boundType: String,
        dependencies: [(name: String?, type: String)] = []
    ) -> DiscoveredBinding {
        let deps = dependencies.map {
            DependencyParameter(
                name: $0.name,
                type: $0.type,
                kind: .providerFunctionParameter,
                location: mockLocation("\(accessPath).swift")
            )
        }
        return .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .function,
                dependencies: deps,
                genericParameterNames: [],
                location: mockLocation("\(accessPath).swift")
            )
        )
    }

    @Test func emptyGraphProducesBareBootstrap() {
        // Empty graph still emits a valid struct so consumers can call
        // `_WireGraph.bootstrap()` unconditionally. The free function
        // is also emitted (returning the empty memberwise init) so the
        // delegation shape is uniform across empty and non-empty graphs.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            """
        #expect(renderWireGraph(imports: [], topologicalOrder: []) == expected)
    }

    @Test func singleNoDependencySingleton() {
        // Construction lives in a free `_wireBootstrap()` at module
        // scope. From there, bare references resolve to module scope
        // without going through `_WireGraph`'s instance members.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let a: A

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let a = A()
                return _WireGraph(a: a)
            }

            """
        #expect(
            renderWireGraph(imports: [], topologicalOrder: [singleton("A")]) == expected
        )
    }

    @Test func threeNodeChainConstructsInDependencyOrder() {
        // C → B → A. Each constructor's argument is an in-scope local
        // bound by a preceding statement.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let c: C
                let b: B
                let a: A

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let c = C()
                let b = B(c: c)
                let a = A(b: b)
                return _WireGraph(c: c, b: b, a: a)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                singleton("C"),
                singleton("B", dependencies: [(name: "c", type: "C")]),
                singleton("A", dependencies: [(name: "b", type: "B")]),
            ]
        )
        #expect(output == expected)
    }

    @Test func wildcardLabelOmittedFromCallSite() {
        // `init(_ a: A)` — the call site must omit the label entirely;
        // emitting `X(_: a)` would be a compile error in the consumer.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let a: A
                let x: X

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let a = A()
                let x = X(a)
                return _WireGraph(a: a, x: x)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                singleton("A"),
                singleton("X", dependencies: [(name: nil, type: "A")]),
            ]
        )
        #expect(output == expected)
    }

    @Test func mixedWildcardAndLabeledArguments() {
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let a: A
                let b: B
                let x: X

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let a = A()
                let b = B()
                let x = X(a, second: b)
                return _WireGraph(a: a, b: b, x: x)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                singleton("A"),
                singleton("B"),
                singleton(
                    "X",
                    dependencies: [(name: nil, type: "A"), (name: "second", type: "B")]
                ),
            ]
        )
        #expect(output == expected)
    }

    @Test func acronymsArePreservedInPropertyNames() {
        // Naive lowercasing keeps internal acronym case intact:
        // `DynamoDBTaskRepository` → `dynamoDBTaskRepository`.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let dynamoDBTaskRepository: DynamoDBTaskRepository

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let dynamoDBTaskRepository = DynamoDBTaskRepository()
                return _WireGraph(dynamoDBTaskRepository: dynamoDBTaskRepository)
            }

            """
        #expect(
            renderWireGraph(
                imports: [],
                topologicalOrder: [singleton("DynamoDBTaskRepository")]
            ) == expected
        )
    }

    // MARK: - @Provides construction

    @Test func providerPropertyConstructionIsBareReference() {
        // @Provides let logger: Logger = ... → `let logger = logger`
        // inside `_wireBootstrap()`. Swift's let-shadowing resolves the
        // RHS to module scope before the local binds, so the same
        // identifier on both sides works correctly.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let logger = logger
                return _WireGraph(logger: logger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [providerProperty("logger", boundType: "Logger")]
        )
        #expect(output == expected)
    }

    @Test func providerWithDottedAccessPathPreservesNamespace() {
        // Static @Provides on `enum Config` → `Config.databaseURL`.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let database: Database

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let database = Config.databaseURL
                return _WireGraph(database: database)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerProperty("Config.databaseURL", boundType: "Database")
            ]
        )
        #expect(output == expected)
    }

    @Test func providerFunctionConstructionCallsWithResolvedArguments() {
        // @Provides func makeRepo(table:) -> Repository, with the table
        // dep coming from another @Provides.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let taskTable: TaskTable
                let repository: Repository

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let taskTable = taskTable
                let repository = makeRepo(table: taskTable)
                return _WireGraph(taskTable: taskTable, repository: repository)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerProperty("taskTable", boundType: "TaskTable"),
                providerFunction(
                    "makeRepo",
                    boundType: "Repository",
                    dependencies: [(name: "table", type: "TaskTable")]
                ),
            ]
        )
        #expect(output == expected)
    }

    @Test func mixedSingletonAndProviderConstruction() {
        // The realistic pipeline: a @Provides supplies a primitive
        // (Logger), a @Singleton consumes it.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let logger: Logger
                let userService: UserService

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let logger = logger
                let userService = UserService(logger: logger)
                return _WireGraph(logger: logger, userService: userService)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerProperty("logger", boundType: "Logger"),
                singleton(
                    "UserService",
                    dependencies: [(name: "logger", type: "Logger")]
                ),
            ]
        )
        #expect(output == expected)
    }

    // MARK: - Sanitisation

    @Test func genericInstantiationProducesOfSeparatedPropertyName() {
        // Repository<TaskTable> → repositoryOfTaskTable. The bound
        // type is preserved verbatim in the construction call.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let repositoryOfTaskTable: Repository<TaskTable>

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let repositoryOfTaskTable = makeRepo()
                return _WireGraph(repositoryOfTaskTable: repositoryOfTaskTable)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerFunction("makeRepo", boundType: "Repository<TaskTable>")
            ]
        )
        #expect(output == expected)
    }

    @Test func multipleGenericParametersUseAndSeparator() {
        // Pair<Left, Right> → pairOfLeftAndRight.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let pairOfLeftAndRight: Pair<Left, Right>

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let pairOfLeftAndRight = makePair()
                return _WireGraph(pairOfLeftAndRight: pairOfLeftAndRight)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerFunction("makePair", boundType: "Pair<Left, Right>")
            ]
        )
        #expect(output == expected)
    }

    // MARK: - Imports

    @Test func importsAreEmittedSortedAndDeduplicated() {
        let expected = """
            // Generated by WireGen — do not edit.

            import Bar
            import Baz
            import Foo

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            """
        let output = renderWireGraph(
            imports: ["import Foo", "import Bar", "import Foo", "import Baz"],
            topologicalOrder: []
        )
        #expect(output == expected)
    }

    @Test func importsArePreservedVerbatimWithModifiers() {
        // Access modifiers like @testable and @_implementationOnly are
        // captured verbatim by `discoverImports` and emitted as-is.
        let expected = """
            // Generated by WireGen — do not edit.

            @_implementationOnly import OSLog
            @testable import Internals
            import Foundation

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            """
        let output = renderWireGraph(
            imports: [
                "import Foundation",
                "@testable import Internals",
                "@_implementationOnly import OSLog",
            ],
            topologicalOrder: []
        )
        #expect(output == expected)
    }

    // MARK: - Per-container structs

    @Test func singleContainerEmitsItsOwnStructAlongsideEmptyDefault() {
        // When the user has only @Container-routed bindings (no
        // module-scope ones), the default `_WireGraph` is still emitted
        // as an empty struct so consumers can call its bootstrap
        // unconditionally; the container struct emits alongside it.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            internal struct _TestContainerWireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _TestContainerWireGraph {
                    try await _wireBootstrapTestContainer()
                }
            }

            private func _wireBootstrapTestContainer() async throws -> _TestContainerWireGraph {
                let logger = TestContainer.logger
                return _TestContainerWireGraph(logger: logger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            containerTopologicalOrders: [
                "TestContainer": [providerProperty("TestContainer.logger", boundType: "Logger")]
            ]
        )
        #expect(output == expected)
    }

    @Test func defaultAndContainerBothEmitSideBySide() {
        // The default graph and a container coexist independently —
        // each gets its own struct + bootstrap free function. Bindings
        // are scoped to their respective graphs; nothing crosses.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let logger = Logger()
                return _WireGraph(logger: logger)
            }

            internal struct _TestContainerWireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _TestContainerWireGraph {
                    try await _wireBootstrapTestContainer()
                }
            }

            private func _wireBootstrapTestContainer() async throws -> _TestContainerWireGraph {
                let logger = TestContainer.mockLogger
                return _TestContainerWireGraph(logger: logger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [singleton("Logger")],
            containerTopologicalOrders: [
                "TestContainer": [providerProperty("TestContainer.mockLogger", boundType: "Logger")]
            ]
        )
        #expect(output == expected)
    }

    @Test func nestedSingletonUsesQualifiedTypeNameForConstructionAndStoredPropertyType() {
        // A `@Singleton` declared inside a `@Container` has a qualified
        // type name (`TestContainer.MockService`). Both the stored-
        // property type annotation and the construction call use the
        // qualified form — required because `_<Container>WireGraph`
        // and its `_wireBootstrap...` free function live at module
        // scope, where unqualified `MockService` doesn't resolve.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            internal struct _TestContainerWireGraph: Sendable {
                let mockService: TestContainer.MockService

                static func bootstrap() async throws -> _TestContainerWireGraph {
                    try await _wireBootstrapTestContainer()
                }
            }

            private func _wireBootstrapTestContainer() async throws -> _TestContainerWireGraph {
                let mockService = TestContainer.MockService()
                return _TestContainerWireGraph(mockService: mockService)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            containerTopologicalOrders: [
                "TestContainer": [
                    singleton(
                        "MockService",
                        qualifiedTypeName: "TestContainer.MockService"
                    )
                ]
            ]
        )
        #expect(output == expected)
    }

    @Test func multipleContainersAreEmittedInSortedOrder() {
        // Container ordering in the output is deterministic — sorted
        // alphabetically by container name. Critical so successive
        // builds of the same source produce byte-identical output.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            internal struct _AlphaWireGraph: Sendable {
                let a: A

                static func bootstrap() async throws -> _AlphaWireGraph {
                    try await _wireBootstrapAlpha()
                }
            }

            private func _wireBootstrapAlpha() async throws -> _AlphaWireGraph {
                let a = Alpha.a
                return _AlphaWireGraph(a: a)
            }

            internal struct _BravoWireGraph: Sendable {
                let b: B

                static func bootstrap() async throws -> _BravoWireGraph {
                    try await _wireBootstrapBravo()
                }
            }

            private func _wireBootstrapBravo() async throws -> _BravoWireGraph {
                let b = Bravo.b
                return _BravoWireGraph(b: b)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            containerTopologicalOrders: [
                // Insertion order intentionally non-alphabetical to
                // confirm sorted output.
                "Bravo": [providerProperty("Bravo.b", boundType: "B")],
                "Alpha": [providerProperty("Alpha.a", boundType: "A")],
            ]
        )
        #expect(output == expected)
    }

    // MARK: - renderWireKeyChecks

    /// Build a keyed `@Provides` property binding for the key-checks
    /// suite — like `providerProperty` but with `keyIdentifier`.
    private func keyedProperty(
        _ accessPath: String,
        boundType: String,
        key: String,
        line: Int = 1,
        column: Int = 1,
        sourcePath: String? = nil
    ) -> DiscoveredBinding {
        .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: WireGenCore.SourceLocation(
                    file: sourcePath ?? "\(accessPath).swift",
                    line: line,
                    column: column
                ),
                keyIdentifier: key
            )
        )
    }

    /// Build a singleton with one keyed `@Inject` dependency, located
    /// at the given line/column. Lets each test pin a precise
    /// `#sourceLocation` for the assertion call.
    private func consumerWithKeyedDep(
        _ name: String,
        depName: String,
        depType: String,
        depKey: String,
        depLine: Int = 1,
        depColumn: Int = 1,
        depSourcePath: String? = nil
    ) -> DiscoveredBinding {
        .scopeBound(
            DiscoveredScopeBoundType(
                typeName: name,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: [
                    DependencyParameter(
                        name: depName,
                        type: depType,
                        kind: .injectProperty,
                        location: WireGenCore.SourceLocation(
                            file: depSourcePath ?? "\(name).swift",
                            line: depLine,
                            column: depColumn
                        ),
                        keyIdentifier: depKey
                    )
                ],
                location: mockLocation("\(name).swift")
            )
        )
    }

    @Test func keyChecksEmptyInputProducesHeaderOnlyFile() {
        // No bindings at all → file is just the header comment, no
        // functions. SPM still gets the declared output file.
        let output = renderWireKeyChecks(imports: [], allBindings: [])
        #expect(output.contains("// Generated by WireGen"))
        #expect(!output.contains("_wireTypeCheck_"))
        #expect(!output.contains("_check"))
    }

    @Test func keyChecksUnkeyedBindingsProduceNoFunctions() {
        // Unkeyed `@Provides` and `@Inject` don't participate in the
        // key-check file at all — there's nothing to check.
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                providerProperty("logger", boundType: "Logger"),
                singleton("App"),
            ]
        )
        #expect(!output.contains("_wireTypeCheck_"))
    }

    @Test func keyedProviderProducesCheckFunction() {
        // A single keyed `@Provides` produces one check function with
        // one `_check` call wrapped in `#sourceLocation` directives.
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                keyedProperty(
                    "primaryDB",
                    boundType: "Database",
                    key: "Database.primary",
                    line: 5,
                    sourcePath: "App.swift"
                )
            ]
        )
        #expect(output.contains("private func _wireTypeCheck_1()"))
        #expect(output.contains("func _check<T>(_: BindingKey<T>, _: T.Type) {}"))
        #expect(output.contains("#sourceLocation(file: \"App.swift\", line: 5)"))
        #expect(output.contains("_check(Database.primary, Database.self)"))
        #expect(output.contains("#sourceLocation()"))
    }

    @Test func keyedDependencyProducesCheckFunction() {
        // The consumer side also contributes a check site: a keyed
        // `@Inject` on a property.
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                consumerWithKeyedDep(
                    "UserRepo",
                    depName: "db",
                    depType: "Database",
                    depKey: "Database.primary",
                    depLine: 7,
                    depSourcePath: "UserRepo.swift"
                )
            ]
        )
        #expect(output.contains("private func _wireTypeCheck_1()"))
        #expect(output.contains("#sourceLocation(file: \"UserRepo.swift\", line: 7)"))
        #expect(output.contains("_check(Database.primary, Database.self)"))
    }

    @Test func sameKeyAndTypeAtMultipleSitesDedupesToOneFunction() {
        // Producer + two consumers all using `(Database.primary,
        // Database)` produce ONE function with THREE `_check` calls,
        // each at its own `#sourceLocation`. Dedup at the (key, type)
        // level; per-site attribution within the function.
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                keyedProperty(
                    "primaryDB",
                    boundType: "Database",
                    key: "Database.primary",
                    line: 3,
                    sourcePath: "Wiring.swift"
                ),
                consumerWithKeyedDep(
                    "UserRepo",
                    depName: "db",
                    depType: "Database",
                    depKey: "Database.primary",
                    depLine: 5,
                    depSourcePath: "UserRepo.swift"
                ),
                consumerWithKeyedDep(
                    "Sessions",
                    depName: "db",
                    depType: "Database",
                    depKey: "Database.primary",
                    depLine: 9,
                    depSourcePath: "Sessions.swift"
                ),
            ]
        )
        // Exactly one function.
        #expect(output.contains("_wireTypeCheck_1()"))
        #expect(!output.contains("_wireTypeCheck_2"))
        // Three source-location anchors (one per site).
        let sourceLocOpenings = output.split(separator: "#sourceLocation(file:").count - 1
        #expect(sourceLocOpenings == 3)
        #expect(output.contains("\"Wiring.swift\", line: 3"))
        #expect(output.contains("\"UserRepo.swift\", line: 5"))
        #expect(output.contains("\"Sessions.swift\", line: 9"))
    }

    @Test func differentKeysProduceSeparateFunctions() {
        // Different keys on the same type → distinct check functions.
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                keyedProperty(
                    "primaryDB",
                    boundType: "Database",
                    key: "Database.primary"
                ),
                keyedProperty(
                    "replicaDB",
                    boundType: "Database",
                    key: "Database.replica"
                ),
            ]
        )
        #expect(output.contains("_wireTypeCheck_1()"))
        #expect(output.contains("_wireTypeCheck_2()"))
        #expect(output.contains("_check(Database.primary, Database.self)"))
        #expect(output.contains("_check(Database.replica, Database.self)"))
    }

    @Test func differentTypesProduceSeparateFunctions() {
        // Same key text, different types → distinct check functions.
        // (Pathological in practice — keys are typed via `BindingKey<T>`
        // so `Database.primary` is `BindingKey<Database>`. This test
        // pins the discrimination behaviour regardless.)
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                keyedProperty("a", boundType: "Database", key: "shared"),
                keyedProperty("b", boundType: "Cache", key: "shared"),
            ]
        )
        #expect(output.contains("_wireTypeCheck_1()"))
        #expect(output.contains("_wireTypeCheck_2()"))
    }

    @Test func anyProtocolBindingsAreSkipped() {
        // `any P` existentials can't satisfy the generic helper's
        // `T == T` unification cleanly, so we skip emission. Mismatches
        // at these sites fall back to the build plugin's missing-
        // binding diagnostic at codegen.
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                keyedProperty(
                    "fancyLogger",
                    boundType: "any Logger",
                    key: "Logger.fancy"
                )
            ]
        )
        #expect(!output.contains("_wireTypeCheck_"))
    }

    @Test func someProtocolBindingsAreSkipped() {
        // Same treatment for opaque types — concrete `T` unification
        // isn't available at the build-plugin level.
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                consumerWithKeyedDep(
                    "Consumer",
                    depName: "log",
                    depType: "some Logger",
                    depKey: "Logger.fancy"
                )
            ]
        )
        #expect(!output.contains("_wireTypeCheck_"))
    }

    @Test func keyedProviderInGraphGetsKeyedAccessorName() {
        // A keyed `@Provides Database` paired with the unkeyed
        // `Database`-typed binding has to get a distinct identifier
        // for both the stored property on `_WireGraph` and the local
        // in `_wireBootstrap()`. `identifierName(forType:key:)` inserts
        // a `Keyed` infix between the type-derived prefix and the
        // sanitised key suffix — verbose but unambiguous, and the
        // sentinel infix keeps unkeyed type-named bindings safe from
        // collision. The integration test exercises this end-to-end
        // through the real build plugin; this unit test pins the
        // contract in-process where it counts toward coverage.
        let keyedDB: DiscoveredBinding = .provider(
            DiscoveredProvider(
                boundType: "Database",
                accessPath: "primaryDB",
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("DB.swift"),
                keyIdentifier: "Database.primary"
            )
        )
        let unkeyedDB: DiscoveredBinding = .provider(
            DiscoveredProvider(
                boundType: "Database",
                accessPath: "defaultDB",
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("DB.swift"),
                keyIdentifier: nil
            )
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [unkeyedDB, keyedDB]
        )
        // Both accessors present, named for their identity.
        #expect(output.contains("let database: Database"))
        #expect(output.contains("let databaseKeyedDatabasePrimary: Database"))
        // Construction locals match the accessor names. RHS is the
        // provider's accessPath, which differs from the identifier.
        #expect(output.contains("let database = defaultDB"))
        #expect(output.contains("let databaseKeyedDatabasePrimary = primaryDB"))
    }

    @Test func keyedBindingWithDottedKeyCapitalizesEachSegment() {
        // Multi-segment key (`Module.shared.primary`) on a binding
        // whose type doesn't match the leading segment — so the
        // prefix-strip in `identifierName` is a no-op and the full
        // dotted text reaches `sanitizeKeyComponents`. Each dot
        // becomes a segment boundary: dropped, with the next letter
        // upper-cased. Composed suffix is `ModuleSharedPrimary`,
        // appended to the type-derived prefix.
        let exotic: DiscoveredBinding = .provider(
            DiscoveredProvider(
                boundType: "Database",
                accessPath: "exoticDB",
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("DB.swift"),
                keyIdentifier: "Module.shared.primary"
            )
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [exotic]
        )
        #expect(output.contains("let databaseKeyedModuleSharedPrimary: Database"))
    }

    @Test func keyedBindingWithBareKeyAppendsCapitalizedSuffix() {
        // A bare (non-type-qualified) key — `let alternate =
        // BindingKey<...>()` at file scope, referenced as
        // `@Provides(alternate)`. The key text doesn't have a leading
        // `<type>.` to strip, so the suffix is the upper-camelled key
        // appended verbatim. Exercises the path where the
        // `effectiveKey == key` after no-op prefix-strip.
        let alternateDB: DiscoveredBinding = .provider(
            DiscoveredProvider(
                boundType: "Database",
                accessPath: "altDB",
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("DB.swift"),
                keyIdentifier: "alternate"
            )
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [alternateDB]
        )
        #expect(output.contains("let databaseKeyedAlternate: Database"))
    }

    @Test func keyedDependencyResolvesToKeyedLocalName() {
        // A consumer with a keyed `@Inject` dep must resolve to the
        // keyed local name in the construction call — otherwise it'd
        // bind to whatever happens to be at the unkeyed slot. This
        // pins the `renderArguments` path through
        // `identifierName(forType:key:)`.
        let keyedDB: DiscoveredBinding = .provider(
            DiscoveredProvider(
                boundType: "Database",
                accessPath: "primaryDB",
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("DB.swift"),
                keyIdentifier: "Database.primary"
            )
        )
        let consumer: DiscoveredBinding = .scopeBound(
            DiscoveredScopeBoundType(
                typeName: "UserRepo",
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: [
                    DependencyParameter(
                        name: "db",
                        type: "Database",
                        kind: .injectProperty,
                        location: mockLocation("UserRepo.swift"),
                        keyIdentifier: "Database.primary"
                    )
                ],
                location: mockLocation("UserRepo.swift")
            )
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [keyedDB, consumer]
        )
        // Argument value uses the keyed local name, not the bare
        // `database` (which doesn't exist in this graph anyway).
        #expect(output.contains("let userRepo = UserRepo(db: databaseKeyedDatabasePrimary)"))
    }

    @Test func keyChecksSameFileSitesSortByLineWithinFunction() {
        // Two sites for the same `(key, type)` pair in the same file
        // but different lines. `locationOrder`'s line fallback orders
        // them ascending, so the lower-line `#sourceLocation` is
        // emitted first inside the dedup'd function body.
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                keyedProperty(
                    "primaryDB",
                    boundType: "Database",
                    key: "Database.primary",
                    line: 9,
                    sourcePath: "App.swift"
                ),
                consumerWithKeyedDep(
                    "UserRepo",
                    depName: "db",
                    depType: "Database",
                    depKey: "Database.primary",
                    depLine: 3,
                    depSourcePath: "App.swift"
                ),
            ]
        )
        // One function (dedup'd), three #sourceLocation lines total
        // (open at line 3, close, open at line 9, close, plus the
        // final close). The line-3 opening comes before line-9.
        let line3 = output.firstRange(of: "\"App.swift\", line: 3")
        let line9 = output.firstRange(of: "\"App.swift\", line: 9")
        #expect(line3 != nil)
        #expect(line9 != nil)
        if let line3, let line9 {
            #expect(line3.lowerBound < line9.lowerBound)
        }
    }

    @Test func keyChecksSameFileAndLineSitesSortByColumn() {
        // Two sites with identical file and line but different
        // columns — the column-fallback branch of `locationOrder`.
        // Rare in practice (two annotations on the same line) but
        // pins the comparator's tail.
        let output = renderWireKeyChecks(
            imports: [],
            allBindings: [
                keyedProperty(
                    "primaryDB",
                    boundType: "Database",
                    key: "Database.primary",
                    line: 5,
                    column: 20,
                    sourcePath: "App.swift"
                ),
                consumerWithKeyedDep(
                    "UserRepo",
                    depName: "db",
                    depType: "Database",
                    depKey: "Database.primary",
                    depLine: 5,
                    depColumn: 5,
                    depSourcePath: "App.swift"
                ),
            ]
        )
        // The renderer doesn't emit the column in the `#sourceLocation`
        // directive (Swift's directive supports `file:` and `line:`
        // only), so we can't compare on column directly in the output.
        // Instead, check that both sites contributed `_check` calls in
        // a single function — both sites are deduped to the same
        // `(key, type)` pair so they share the function body. The
        // sort uses column to order them deterministically.
        let sourceLocOpenings = output.split(separator: "#sourceLocation(file:").count - 1
        #expect(sourceLocOpenings == 2)
    }

    @Test func keyChecksImportsAreEmittedSortedAndDeduplicated() {
        // Mirrors the renderWireGraph contract — duplicate imports are
        // collapsed, output is alphabetical for determinism.
        let output = renderWireKeyChecks(
            imports: ["import Wire", "import Foundation", "import Wire"],
            allBindings: []
        )
        let lineStrings = output.split(separator: "\n").map(String.init)
        let foundationIdx = lineStrings.firstIndex(of: "import Foundation")
        let wireIdx = lineStrings.firstIndex(of: "import Wire")
        #expect(foundationIdx != nil)
        #expect(wireIdx != nil)
        if let foundationIdx, let wireIdx {
            #expect(foundationIdx < wireIdx)
        }
        // Dedup: only one `import Wire` line.
        let wireOccurrences = lineStrings.filter { $0 == "import Wire" }.count
        #expect(wireOccurrences == 1)
    }
}
