import Testing

@testable import WireGenCore

@Suite("CodeEmission")
struct CodeEmissionTests {
    private func mockLocation(_ file: String) -> WireGenCore.SourceLocation {
        WireGenCore.SourceLocation(file: file, line: 1, column: 1)
    }

    private func singleton(
        _ name: String,
        qualifiedTypeName: String? = nil,
        dependencies: [(name: String?, type: String)] = []
    ) -> DiscoveredBinding {
        let deps = dependencies.map {
            DependencyParameter(
                name: $0.name,
                type: $0.type,
                kind: .injectInitParameter,
                location: mockLocation("\(name).swift")
            )
        }
        return .singleton(
            DiscoveredSingleton(
                typeName: name,
                qualifiedTypeName: qualifiedTypeName,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: deps,
                location: mockLocation("\(name).swift")
            )
        )
    }

    private func providerProperty(
        _ accessPath: String,
        boundType: String
    ) -> DiscoveredBinding {
        .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("\(accessPath).swift")
            )
        )
    }

    private func providerFunction(
        _ accessPath: String,
        boundType: String,
        dependencies: [(name: String?, type: String)] = []
    ) -> DiscoveredBinding {
        let deps = dependencies.map {
            DependencyParameter(
                name: $0.name,
                type: $0.type,
                kind: .providerFunctionParameter,
                location: mockLocation("\(accessPath).swift")
            )
        }
        return .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .function,
                dependencies: deps,
                genericParameterNames: [],
                location: mockLocation("\(accessPath).swift")
            )
        )
    }

    @Test func emptyGraphProducesBareBootstrap() {
        // Empty graph still emits a valid struct so consumers can call
        // `_WireGraph.bootstrap()` unconditionally. The free function
        // is also emitted (returning the empty memberwise init) so the
        // delegation shape is uniform across empty and non-empty graphs.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            """
        #expect(renderWireGraph(imports: [], topologicalOrder: []) == expected)
    }

    @Test func singleNoDependencySingleton() {
        // Construction lives in a free `_wireBootstrap()` at module
        // scope. From there, bare references resolve to module scope
        // without going through `_WireGraph`'s instance members.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let a: A

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let a = A()
                return _WireGraph(a: a)
            }

            """
        #expect(
            renderWireGraph(imports: [], topologicalOrder: [singleton("A")]) == expected
        )
    }

    @Test func threeNodeChainConstructsInDependencyOrder() {
        // C → B → A. Each constructor's argument is an in-scope local
        // bound by a preceding statement.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let c: C
                let b: B
                let a: A

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let c = C()
                let b = B(c: c)
                let a = A(b: b)
                return _WireGraph(c: c, b: b, a: a)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                singleton("C"),
                singleton("B", dependencies: [(name: "c", type: "C")]),
                singleton("A", dependencies: [(name: "b", type: "B")]),
            ]
        )
        #expect(output == expected)
    }

    @Test func wildcardLabelOmittedFromCallSite() {
        // `init(_ a: A)` — the call site must omit the label entirely;
        // emitting `X(_: a)` would be a compile error in the consumer.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let a: A
                let x: X

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let a = A()
                let x = X(a)
                return _WireGraph(a: a, x: x)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                singleton("A"),
                singleton("X", dependencies: [(name: nil, type: "A")]),
            ]
        )
        #expect(output == expected)
    }

    @Test func mixedWildcardAndLabeledArguments() {
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let a: A
                let b: B
                let x: X

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let a = A()
                let b = B()
                let x = X(a, second: b)
                return _WireGraph(a: a, b: b, x: x)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                singleton("A"),
                singleton("B"),
                singleton(
                    "X",
                    dependencies: [(name: nil, type: "A"), (name: "second", type: "B")]
                ),
            ]
        )
        #expect(output == expected)
    }

    @Test func acronymsArePreservedInPropertyNames() {
        // Naive lowercasing keeps internal acronym case intact:
        // `DynamoDBTaskRepository` → `dynamoDBTaskRepository`.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let dynamoDBTaskRepository: DynamoDBTaskRepository

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let dynamoDBTaskRepository = DynamoDBTaskRepository()
                return _WireGraph(dynamoDBTaskRepository: dynamoDBTaskRepository)
            }

            """
        #expect(
            renderWireGraph(
                imports: [],
                topologicalOrder: [singleton("DynamoDBTaskRepository")]
            ) == expected
        )
    }

    // MARK: - @Provides construction

    @Test func providerPropertyConstructionIsBareReference() {
        // @Provides let logger: Logger = ... → `let logger = logger`
        // inside `_wireBootstrap()`. Swift's let-shadowing resolves the
        // RHS to module scope before the local binds, so the same
        // identifier on both sides works correctly.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let logger = logger
                return _WireGraph(logger: logger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [providerProperty("logger", boundType: "Logger")]
        )
        #expect(output == expected)
    }

    @Test func providerWithDottedAccessPathPreservesNamespace() {
        // Static @Provides on `enum Config` → `Config.databaseURL`.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let database: Database

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let database = Config.databaseURL
                return _WireGraph(database: database)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerProperty("Config.databaseURL", boundType: "Database")
            ]
        )
        #expect(output == expected)
    }

    @Test func providerFunctionConstructionCallsWithResolvedArguments() {
        // @Provides func makeRepo(table:) -> Repository, with the table
        // dep coming from another @Provides.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let taskTable: TaskTable
                let repository: Repository

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let taskTable = taskTable
                let repository = makeRepo(table: taskTable)
                return _WireGraph(taskTable: taskTable, repository: repository)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerProperty("taskTable", boundType: "TaskTable"),
                providerFunction(
                    "makeRepo",
                    boundType: "Repository",
                    dependencies: [(name: "table", type: "TaskTable")]
                ),
            ]
        )
        #expect(output == expected)
    }

    @Test func mixedSingletonAndProviderConstruction() {
        // The realistic pipeline: a @Provides supplies a primitive
        // (Logger), a @Singleton consumes it.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let logger: Logger
                let userService: UserService

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let logger = logger
                let userService = UserService(logger: logger)
                return _WireGraph(logger: logger, userService: userService)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerProperty("logger", boundType: "Logger"),
                singleton(
                    "UserService",
                    dependencies: [(name: "logger", type: "Logger")]
                ),
            ]
        )
        #expect(output == expected)
    }

    // MARK: - Sanitisation

    @Test func genericInstantiationProducesOfSeparatedPropertyName() {
        // Repository<TaskTable> → repositoryOfTaskTable. The bound
        // type is preserved verbatim in the construction call.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let repositoryOfTaskTable: Repository<TaskTable>

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let repositoryOfTaskTable = makeRepo()
                return _WireGraph(repositoryOfTaskTable: repositoryOfTaskTable)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerFunction("makeRepo", boundType: "Repository<TaskTable>")
            ]
        )
        #expect(output == expected)
    }

    @Test func multipleGenericParametersUseAndSeparator() {
        // Pair<Left, Right> → pairOfLeftAndRight.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let pairOfLeftAndRight: Pair<Left, Right>

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let pairOfLeftAndRight = makePair()
                return _WireGraph(pairOfLeftAndRight: pairOfLeftAndRight)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [
                providerFunction("makePair", boundType: "Pair<Left, Right>")
            ]
        )
        #expect(output == expected)
    }

    // MARK: - Imports

    @Test func importsAreEmittedSortedAndDeduplicated() {
        let expected = """
            // Generated by WireGen — do not edit.

            import Bar
            import Baz
            import Foo

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            """
        let output = renderWireGraph(
            imports: ["import Foo", "import Bar", "import Foo", "import Baz"],
            topologicalOrder: []
        )
        #expect(output == expected)
    }

    @Test func importsArePreservedVerbatimWithModifiers() {
        // Access modifiers like @testable and @_implementationOnly are
        // captured verbatim by `discoverImports` and emitted as-is.
        let expected = """
            // Generated by WireGen — do not edit.

            @_implementationOnly import OSLog
            @testable import Internals
            import Foundation

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            """
        let output = renderWireGraph(
            imports: [
                "import Foundation",
                "@testable import Internals",
                "@_implementationOnly import OSLog",
            ],
            topologicalOrder: []
        )
        #expect(output == expected)
    }

    // MARK: - Per-container structs

    @Test func singleContainerEmitsItsOwnStructAlongsideEmptyDefault() {
        // When the user has only @Container-routed bindings (no
        // module-scope ones), the default `_WireGraph` is still emitted
        // as an empty struct so consumers can call its bootstrap
        // unconditionally; the container struct emits alongside it.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            internal struct _TestContainerWireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _TestContainerWireGraph {
                    try await _wireBootstrapTestContainer()
                }
            }

            private func _wireBootstrapTestContainer() async throws -> _TestContainerWireGraph {
                let logger = TestContainer.logger
                return _TestContainerWireGraph(logger: logger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            containerTopologicalOrders: [
                "TestContainer": [providerProperty("TestContainer.logger", boundType: "Logger")]
            ]
        )
        #expect(output == expected)
    }

    @Test func defaultAndContainerBothEmitSideBySide() {
        // The default graph and a container coexist independently —
        // each gets its own struct + bootstrap free function. Bindings
        // are scoped to their respective graphs; nothing crosses.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let logger = Logger()
                return _WireGraph(logger: logger)
            }

            internal struct _TestContainerWireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _TestContainerWireGraph {
                    try await _wireBootstrapTestContainer()
                }
            }

            private func _wireBootstrapTestContainer() async throws -> _TestContainerWireGraph {
                let logger = TestContainer.mockLogger
                return _TestContainerWireGraph(logger: logger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [singleton("Logger")],
            containerTopologicalOrders: [
                "TestContainer": [providerProperty("TestContainer.mockLogger", boundType: "Logger")]
            ]
        )
        #expect(output == expected)
    }

    @Test func nestedSingletonUsesQualifiedTypeNameForConstructionAndStoredPropertyType() {
        // A `@Singleton` declared inside a `@Container` has a qualified
        // type name (`TestContainer.MockService`). Both the stored-
        // property type annotation and the construction call use the
        // qualified form — required because `_<Container>WireGraph`
        // and its `_wireBootstrap...` free function live at module
        // scope, where unqualified `MockService` doesn't resolve.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            internal struct _TestContainerWireGraph: Sendable {
                let mockService: TestContainer.MockService

                static func bootstrap() async throws -> _TestContainerWireGraph {
                    try await _wireBootstrapTestContainer()
                }
            }

            private func _wireBootstrapTestContainer() async throws -> _TestContainerWireGraph {
                let mockService = TestContainer.MockService()
                return _TestContainerWireGraph(mockService: mockService)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            containerTopologicalOrders: [
                "TestContainer": [
                    singleton(
                        "MockService",
                        qualifiedTypeName: "TestContainer.MockService"
                    )
                ]
            ]
        )
        #expect(output == expected)
    }

    @Test func multipleContainersAreEmittedInSortedOrder() {
        // Container ordering in the output is deterministic — sorted
        // alphabetically by container name. Critical so successive
        // builds of the same source produce byte-identical output.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            internal struct _AlphaWireGraph: Sendable {
                let a: A

                static func bootstrap() async throws -> _AlphaWireGraph {
                    try await _wireBootstrapAlpha()
                }
            }

            private func _wireBootstrapAlpha() async throws -> _AlphaWireGraph {
                let a = Alpha.a
                return _AlphaWireGraph(a: a)
            }

            internal struct _BravoWireGraph: Sendable {
                let b: B

                static func bootstrap() async throws -> _BravoWireGraph {
                    try await _wireBootstrapBravo()
                }
            }

            private func _wireBootstrapBravo() async throws -> _BravoWireGraph {
                let b = Bravo.b
                return _BravoWireGraph(b: b)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            containerTopologicalOrders: [
                // Insertion order intentionally non-alphabetical to
                // confirm sorted output.
                "Bravo": [providerProperty("Bravo.b", boundType: "B")],
                "Alpha": [providerProperty("Alpha.a", boundType: "A")],
            ]
        )
        #expect(output == expected)
    }
}
