import Testing

@testable import WireGenCore

@Suite("CodeEmission")
struct CodeEmissionTests {
    private func singleton(
        _ name: String,
        dependencies: [(name: String?, type: String)] = []
    ) -> DiscoveredBinding {
        let deps = dependencies.map {
            DependencyParameter(name: $0.name, type: $0.type, kind: .injectInitParameter)
        }
        return .singleton(
            DiscoveredSingleton(
                typeName: name,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: deps,
                sourcePath: "\(name).swift"
            )
        )
    }

    private func providerProperty(
        _ accessPath: String,
        boundType: String
    ) -> DiscoveredBinding {
        .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                sourcePath: "\(accessPath).swift"
            )
        )
    }

    private func providerFunction(
        _ accessPath: String,
        boundType: String,
        dependencies: [(name: String?, type: String)] = []
    ) -> DiscoveredBinding {
        let deps = dependencies.map {
            DependencyParameter(
                name: $0.name,
                type: $0.type,
                kind: .providerFunctionParameter
            )
        }
        return .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .function,
                dependencies: deps,
                genericParameterNames: [],
                sourcePath: "\(accessPath).swift"
            )
        )
    }

    @Test func emptyGraphProducesBareBootstrap() {
        // Empty graph still emits a valid struct so consumers can call
        // `_WireGraph.bootstrap()` unconditionally.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    _WireGraph()
                }
            }

            """
        #expect(renderWireGraph(moduleName: "App", topologicalOrder: []) == expected)
    }

    @Test func singleNoDependencySingletonIsModuleQualified() {
        // The construction RHS is qualified with the module name so the
        // local `a` doesn't recursively shadow a hypothetical module-
        // scope `let a` declared by the user.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let a: A

                static func bootstrap() async throws -> _WireGraph {
                    let a = App.A()
                    return _WireGraph(a: a)
                }
            }

            """
        #expect(
            renderWireGraph(moduleName: "App", topologicalOrder: [singleton("A")]) == expected
        )
    }

    @Test func threeNodeChainConstructsInDependencyOrder() {
        // C → B → A. Each constructor's argument is an in-scope local
        // bound by a preceding statement. Bootstrap is locked to
        // `async throws` regardless of whether current bindings need
        // it — M6's lifecycle work needs the option without rippling a
        // breaking change through every consumer's call site.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let c: C
                let b: B
                let a: A

                static func bootstrap() async throws -> _WireGraph {
                    let c = App.C()
                    let b = App.B(c: c)
                    let a = App.A(b: b)
                    return _WireGraph(c: c, b: b, a: a)
                }
            }

            """
        let output = renderWireGraph(
            moduleName: "App",
            topologicalOrder: [
                singleton("C"),
                singleton("B", dependencies: [(name: "c", type: "C")]),
                singleton("A", dependencies: [(name: "b", type: "B")]),
            ]
        )
        #expect(output == expected)
    }

    @Test func wildcardLabelOmittedFromCallSite() {
        // `init(_ a: A)` — the call site must omit the label entirely;
        // emitting `X(_: a)` would be a compile error in the consumer.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let a: A
                let x: X

                static func bootstrap() async throws -> _WireGraph {
                    let a = App.A()
                    let x = App.X(a)
                    return _WireGraph(a: a, x: x)
                }
            }

            """
        let output = renderWireGraph(
            moduleName: "App",
            topologicalOrder: [
                singleton("A"),
                singleton("X", dependencies: [(name: nil, type: "A")]),
            ]
        )
        #expect(output == expected)
    }

    @Test func mixedWildcardAndLabeledArguments() {
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let a: A
                let b: B
                let x: X

                static func bootstrap() async throws -> _WireGraph {
                    let a = App.A()
                    let b = App.B()
                    let x = App.X(a, second: b)
                    return _WireGraph(a: a, b: b, x: x)
                }
            }

            """
        let output = renderWireGraph(
            moduleName: "App",
            topologicalOrder: [
                singleton("A"),
                singleton("B"),
                singleton(
                    "X",
                    dependencies: [(name: nil, type: "A"), (name: "second", type: "B")]
                ),
            ]
        )
        #expect(output == expected)
    }

    @Test func acronymsArePreservedInPropertyNames() {
        // Naive lowercasing keeps internal acronym case intact:
        // `DynamoDBTaskRepository` → `dynamoDBTaskRepository`.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let dynamoDBTaskRepository: DynamoDBTaskRepository

                static func bootstrap() async throws -> _WireGraph {
                    let dynamoDBTaskRepository = App.DynamoDBTaskRepository()
                    return _WireGraph(dynamoDBTaskRepository: dynamoDBTaskRepository)
                }
            }

            """
        #expect(
            renderWireGraph(
                moduleName: "App",
                topologicalOrder: [singleton("DynamoDBTaskRepository")]
            ) == expected
        )
    }

    // MARK: - @Provides construction

    @Test func providerPropertyConstructionIsBareModuleQualifiedReference() {
        // @Provides let logger: Logger = ... → `let logger = Module.logger`
        // (no parens — it's a property access, not a function call).
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _WireGraph {
                    let logger = App.logger
                    return _WireGraph(logger: logger)
                }
            }

            """
        let output = renderWireGraph(
            moduleName: "App",
            topologicalOrder: [providerProperty("logger", boundType: "Logger")]
        )
        #expect(output == expected)
    }

    @Test func providerWithDottedAccessPathPreservesNamespace() {
        // Static @Provides on `enum Config` → `App.Config.databaseURL`.
        // The dotted access path is preserved verbatim, qualified by
        // the module on the way in.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let database: Database

                static func bootstrap() async throws -> _WireGraph {
                    let database = App.Config.databaseURL
                    return _WireGraph(database: database)
                }
            }

            """
        let output = renderWireGraph(
            moduleName: "App",
            topologicalOrder: [
                providerProperty("Config.databaseURL", boundType: "Database")
            ]
        )
        #expect(output == expected)
    }

    @Test func providerFunctionConstructionCallsWithResolvedArguments() {
        // @Provides func makeRepo(table:) -> Repository, with the table
        // dep coming from another @Provides. The function call site
        // is module-qualified and includes the resolved argument.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let taskTable: TaskTable
                let repository: Repository

                static func bootstrap() async throws -> _WireGraph {
                    let taskTable = App.taskTable
                    let repository = App.makeRepo(table: taskTable)
                    return _WireGraph(taskTable: taskTable, repository: repository)
                }
            }

            """
        let output = renderWireGraph(
            moduleName: "App",
            topologicalOrder: [
                providerProperty("taskTable", boundType: "TaskTable"),
                providerFunction(
                    "makeRepo",
                    boundType: "Repository",
                    dependencies: [(name: "table", type: "TaskTable")]
                ),
            ]
        )
        #expect(output == expected)
    }

    @Test func mixedSingletonAndProviderConstruction() {
        // The realistic pipeline: a @Provides supplies a primitive
        // (Logger), a @Singleton consumes it.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let logger: Logger
                let userService: UserService

                static func bootstrap() async throws -> _WireGraph {
                    let logger = App.logger
                    let userService = App.UserService(logger: logger)
                    return _WireGraph(logger: logger, userService: userService)
                }
            }

            """
        let output = renderWireGraph(
            moduleName: "App",
            topologicalOrder: [
                providerProperty("logger", boundType: "Logger"),
                singleton(
                    "UserService",
                    dependencies: [(name: "logger", type: "Logger")]
                ),
            ]
        )
        #expect(output == expected)
    }

    // MARK: - Sanitisation

    @Test func genericInstantiationProducesOfSeparatedPropertyName() {
        // Repository<TaskTable> → repositoryOfTaskTable. The bound
        // type is preserved verbatim in the construction call.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let repositoryOfTaskTable: Repository<TaskTable>

                static func bootstrap() async throws -> _WireGraph {
                    let repositoryOfTaskTable = App.makeRepo()
                    return _WireGraph(repositoryOfTaskTable: repositoryOfTaskTable)
                }
            }

            """
        let output = renderWireGraph(
            moduleName: "App",
            topologicalOrder: [
                providerFunction("makeRepo", boundType: "Repository<TaskTable>")
            ]
        )
        #expect(output == expected)
    }

    @Test func multipleGenericParametersUseAndSeparator() {
        // Pair<Left, Right> → pairOfLeftAndRight. The And separator
        // distinguishes from a hypothetical PairLeftRight type that
        // would also exist.
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let pairOfLeftAndRight: Pair<Left, Right>

                static func bootstrap() async throws -> _WireGraph {
                    let pairOfLeftAndRight = App.makePair()
                    return _WireGraph(pairOfLeftAndRight: pairOfLeftAndRight)
                }
            }

            """
        let output = renderWireGraph(
            moduleName: "App",
            topologicalOrder: [
                providerFunction("makePair", boundType: "Pair<Left, Right>")
            ]
        )
        #expect(output == expected)
    }
}
