import Testing

@testable import WireGenCore

@Suite("SeedScopeEmission")
struct SeedScopeEmissionTests {
    // MARK: - Helpers

    private func singleton(_ name: String) -> DiscoveredBinding {
        .scopeBound(
            DiscoveredScopeBoundType(
                typeName: name,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: [],
                location: mockLocation("\(name).swift")
            )
        )
    }

    private func scopedSingleton(
        _ name: String,
        seed: String,
        dependencies: [(name: String?, type: String)] = []
    ) -> DiscoveredBinding {
        let deps = dependencies.map {
            DependencyParameter(
                name: $0.name,
                type: $0.type,
                kind: .injectInitParameter,
                location: mockLocation("\(name).swift")
            )
        }
        return .scopeBound(
            DiscoveredScopeBoundType(
                typeName: name,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: deps,
                location: mockLocation("\(name).swift"),
                scopeKey: ScopeKey(seed: seed)
            )
        )
    }

    private func syntheticProvider(boundType: String, accessPath: String) -> DiscoveredBinding {
        .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("<synthetic>")
            )
        )
    }

    // MARK: - Tests

    @Test func seedScopeWithOnlySeedAliasingProducesScopeStruct() {
        // Smallest possible seed-scope graph: one `@Scoped` type whose
        // only dependency is the seed itself. The bootstrap aliases
        // `seed` to a local matching the seed's sanitised name; the
        // scope binding constructs against that local. No singleton
        // borrows are needed.
        let scope = SeedScopeEmission(
            seedTypeExpression: "HBRequestSeed",
            identifierSuffix: "HBRequestSeed",
            topologicalOrder: [
                syntheticProvider(boundType: "HBRequestSeed", accessPath: "seed"),
                scopedSingleton(
                    "RequestLogger",
                    seed: "HBRequestSeed",
                    dependencies: [(name: "seed", type: "HBRequestSeed")]
                ),
            ],
            borrowedBindingPropertyNames: []
        )
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            internal struct _HBRequestSeedWireScope: Sendable {
                let hBRequestSeed: HBRequestSeed
                let requestLogger: RequestLogger

                static func bootstrap(seed: HBRequestSeed, singletons: _WireGraph) async throws -> _HBRequestSeedWireScope {
                    try await _wireBootstrapHBRequestSeedScope(seed: seed, singletons: singletons)
                }
            }

            private func _wireBootstrapHBRequestSeedScope(seed: HBRequestSeed, singletons: _WireGraph) async throws -> _HBRequestSeedWireScope {
                let hBRequestSeed = seed
                let requestLogger = RequestLogger(seed: hBRequestSeed)
                return _HBRequestSeedWireScope(hBRequestSeed: hBRequestSeed, requestLogger: requestLogger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            seedScopeOrders: [scope]
        )
        #expect(output == expected)
    }

    @Test func seedScopeBorrowingSingletonsExcludesThemFromStoredProperties() {
        // Singletons borrowed via the synthetic-borrow mechanism appear
        // as locals in the bootstrap body (`let logger = singletons.logger`)
        // but are NOT stored on the scope struct — the caller already
        // owns the singletons graph and double-storing would just
        // duplicate references. The scope struct stores only the seed
        // and the scope-bound bindings; `borrowedBindingPropertyNames`
        // is the filter set.
        let scope = SeedScopeEmission(
            seedTypeExpression: "HBRequestSeed",
            identifierSuffix: "HBRequestSeed",
            topologicalOrder: [
                syntheticProvider(boundType: "Logger", accessPath: "singletons.logger"),
                syntheticProvider(boundType: "HBRequestSeed", accessPath: "seed"),
                scopedSingleton(
                    "RequestLogger",
                    seed: "HBRequestSeed",
                    dependencies: [
                        (name: "base", type: "Logger"),
                        (name: "seed", type: "HBRequestSeed"),
                    ]
                ),
            ],
            borrowedBindingPropertyNames: ["logger"]
        )
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Sendable {
                let logger: Logger

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let logger = Logger()
                return _WireGraph(logger: logger)
            }

            internal struct _HBRequestSeedWireScope: Sendable {
                let hBRequestSeed: HBRequestSeed
                let requestLogger: RequestLogger

                static func bootstrap(seed: HBRequestSeed, singletons: _WireGraph) async throws -> _HBRequestSeedWireScope {
                    try await _wireBootstrapHBRequestSeedScope(seed: seed, singletons: singletons)
                }
            }

            private func _wireBootstrapHBRequestSeedScope(seed: HBRequestSeed, singletons: _WireGraph) async throws -> _HBRequestSeedWireScope {
                let logger = singletons.logger
                let hBRequestSeed = seed
                let requestLogger = RequestLogger(base: logger, seed: hBRequestSeed)
                return _HBRequestSeedWireScope(hBRequestSeed: hBRequestSeed, requestLogger: requestLogger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [singleton("Logger")],
            seedScopeOrders: [scope]
        )
        #expect(output == expected)
    }

    @Test func multipleSeedScopesEmitInSortedOrder() {
        // Two distinct seed types produce two `_<Suffix>WireScope`
        // structs, emitted in identifier-suffix sort order regardless
        // of insertion order. Deterministic output matters for stable
        // builds and diff readability.
        let request = SeedScopeEmission(
            seedTypeExpression: "RequestSeed",
            identifierSuffix: "RequestSeed",
            topologicalOrder: [syntheticProvider(boundType: "RequestSeed", accessPath: "seed")],
            borrowedBindingPropertyNames: []
        )
        let job = SeedScopeEmission(
            seedTypeExpression: "JobSeed",
            identifierSuffix: "JobSeed",
            topologicalOrder: [syntheticProvider(boundType: "JobSeed", accessPath: "seed")],
            borrowedBindingPropertyNames: []
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            // Insertion order intentionally non-alphabetical to confirm
            // sorted output.
            seedScopeOrders: [request, job]
        )
        // JobSeed sorts before RequestSeed alphabetically; chop the
        // output at each struct's marker and assert the remainder
        // shrinks from the JobSeed split (later marker still present)
        // to the RequestSeed split (last struct in the output).
        let jobMarker = "_JobSeedWireScope"
        let requestMarker = "_RequestSeedWireScope"
        #expect(output.contains(jobMarker))
        #expect(output.contains(requestMarker))
        let afterJobSplit = output.split(separator: jobMarker).last.map(String.init) ?? ""
        let afterRequestSplit = output.split(separator: requestMarker).last.map(String.init) ?? ""
        // After splitting on JobSeed, the remainder still contains the
        // RequestSeed marker (RequestSeed comes later). After splitting
        // on RequestSeed, the remainder does not contain JobSeed (no
        // later occurrences).
        #expect(afterJobSplit.contains(requestMarker))
        #expect(!afterRequestSplit.contains(jobMarker))
    }

    @Test func seedScopeGenericSeedTypeProducesSanitisedSuffix() {
        // A seed expression like `TenantSeed<String>` sanitises to
        // `TenantSeedOfString` for the struct name, mirroring the
        // generic-instantiation convention used for binding property
        // names elsewhere in emission.
        let scope = SeedScopeEmission(
            seedTypeExpression: "TenantSeed<String>",
            identifierSuffix: sanitizeIdentifier("TenantSeed<String>"),
            topologicalOrder: [
                syntheticProvider(boundType: "TenantSeed<String>", accessPath: "seed")
            ],
            borrowedBindingPropertyNames: []
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            seedScopeOrders: [scope]
        )
        #expect(output.contains("internal struct _TenantSeedOfStringWireScope: Sendable {"))
        #expect(
            output.contains(
                "static func bootstrap(seed: TenantSeed<String>, singletons: _WireGraph) async throws"
            )
        )
        #expect(output.contains("private func _wireBootstrapTenantSeedOfStringScope("))
    }
}
