import Testing

@testable import WireGenCore

@Suite("SeedScopeEmission")
struct SeedScopeEmissionTests {
    // MARK: - Helpers

    private func singleton(_ name: String) -> DiscoveredBinding {
        .scopeBound(
            DiscoveredScopeBoundType(
                typeName: name,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: [],
                location: mockLocation("\(name).swift"),
                originModule: testModule
            )
        )
    }

    private func scopedSingleton(
        _ name: String,
        seed: String,
        dependencies: [(name: String?, type: String)] = [],
        teardown: TeardownAction? = nil
    ) -> DiscoveredBinding {
        let deps = dependencies.map {
            DependencyParameter(
                name: $0.name,
                type: $0.type,
                kind: .injectInitParameter,
                location: mockLocation("\(name).swift")
            )
        }
        return .scopeBound(
            DiscoveredScopeBoundType(
                typeName: name,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: deps,
                location: mockLocation("\(name).swift"),
                scopeKey: ScopeKey(seed: seed),
                teardown: teardown,
                originModule: testModule
            )
        )
    }

    private func syntheticProvider(boundType: String, accessPath: String) -> DiscoveredBinding {
        .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("<synthetic>"),
                originModule: testModule
            )
        )
    }

    // MARK: - Tests

    @Test func seedScopeWithOnlySeedAliasingProducesScopeStruct() {
        // Smallest possible seed-scope graph: one `@Scoped` type whose
        // only dependency is the seed itself. The bootstrap aliases
        // `seed` to a local matching the seed's sanitised name; the
        // scope binding constructs against that local. No singleton
        // borrows are needed.
        let scope = SeedScopeEmission(
            seedTypeExpression: "HBRequestSeed",
            identifierSuffix: "HBRequestSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "HBRequestSeed", accessPath: "hBRequestSeed"),
                scopedSingleton(
                    "RequestLogger",
                    seed: "HBRequestSeed",
                    dependencies: [(name: "seed", type: "HBRequestSeed")]
                ),
            ],
            borrowedBindingPropertyNames: []
        )
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Introspectable, Teardownable {

                func introspect() -> WiringModel {
                    WiringModel(bindings: [])
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            internal struct _HBRequestSeedWireScope {
                let hBRequestSeed: HBRequestSeed
                let requestLogger: RequestLogger
            }

            private func _wireBootstrapHBRequestSeedScope(seed hBRequestSeed: HBRequestSeed, wireGraph _wireGraph: _WireGraph) async throws -> _HBRequestSeedWireScope {
                let requestLogger = RequestLogger(seed: hBRequestSeed)
                return _HBRequestSeedWireScope(hBRequestSeed: hBRequestSeed, requestLogger: requestLogger)
            }

            internal enum Wire {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
                static func bootstrapHBRequestSeedScope(seed: HBRequestSeed, wireGraph: _WireGraph) async throws -> _HBRequestSeedWireScope {
                    try await _wireBootstrapHBRequestSeedScope(seed: seed, wireGraph: wireGraph)
                }
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            seedScopeOrders: [scope]
        )
        #expect(output == expected)
    }

    @Test func bridgingProxyEmitsScopeEntryThunkCapturingSingletons() {
        // A `.singleton` proxy over a `@Scoped(seed: RequestSeed)` controller (the bridge case): the
        // main bootstrap emits a `_wireEnterScope` thunk that builds the controller fresh from a seed,
        // capturing the borrowed app singleton (`todoRepository`) as a local, and wires it into the proxy.
        let subject = DiscoveredScopeBoundType(
            typeName: "SessionController",
            typeKind: "struct",
            genericParameterNames: [],
            dependencies: [
                DependencyParameter(
                    name: "seed",
                    type: "RequestSeed",
                    kind: .injectInitParameter,
                    location: mockLocation("S.swift")
                ),
                DependencyParameter(
                    name: "repository",
                    type: "TodoRepository",
                    kind: .injectInitParameter,
                    location: mockLocation("S.swift")
                ),
            ],
            location: mockLocation("S.swift"),
            scopeKey: ScopeKey(seed: "RequestSeed"),
            originModule: testModule
        )
        let proxy = contributorProxyBinding(
            for: subject,
            key: "WireMVCKeys.routeContributors",
            prefix: "_WireRouteContributor_",
            proxyScope: .singleton
        )
        let scope = SeedScopeEmission(
            seedTypeExpression: "RequestSeed",
            identifierSuffix: "RequestSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "RequestSeed", accessPath: "requestSeed"),
                syntheticProvider(boundType: "TodoRepository", accessPath: "_wireGraph.todoRepository"),
                scopedSingleton(
                    "SessionController",
                    seed: "RequestSeed",
                    dependencies: [(name: "seed", type: "RequestSeed"), (name: "repository", type: "TodoRepository")]
                ),
            ],
            borrowedBindingPropertyNames: ["todoRepository"]
        )
        let output = renderWireGraph(
            imports: [],
            // `TodoRepository` before the proxy so its local is bound (and captured) by the time the
            // thunk closure is emitted.
            topologicalOrder: [singleton("TodoRepository"), .scopeBound(proxy)],
            seedScopeOrders: [scope]
        )

        let thunkType = contributorScopeEntryThunkType(seed: "RequestSeed", subject: "SessionController")
        let thunkLocal = identifierName(forType: thunkType, key: nil)
        // The thunk closure builds the controller from the seed, the borrow resolving to the captured
        // singleton local (`todoRepository`), not `_wireGraph.todoRepository`.
        // The closure carries its parameter/effects/`@Sendable` inline and infers its return type (so a
        // generic subject resolves to the concrete backend, not an unspellable `some P` closure return).
        #expect(output.contains("let \(thunkLocal) = { @Sendable (requestSeed: RequestSeed) async throws in"))
        #expect(
            output.contains("let sessionController = SessionController(seed: requestSeed, repository: todoRepository)")
        )
        // The thunk returns the subject alongside the scope's teardown closure (M5.4.5) — here empty, since
        // no scope binding carries a @Teardown.
        #expect(output.contains("let _wireScopeTeardown: @Sendable () async -> [any Error] = {"))
        #expect(output.contains("return (sessionController, _wireScopeTeardown)"))
        // The proxy's `_wireEnterScope` argument wires to the thunk local.
        #expect(output.contains("_WireRouteContributor_SessionController(_wireEnterScope: \(thunkLocal))"))
        // The borrow is never re-constructed as a local inside the thunk.
        #expect(!output.contains("let todoRepository = _wireGraph.todoRepository"))
    }

    @Test func scopeEntryThunkTearsDownScopedBindings() {
        // A `@Scoped` resource carrying a `@Teardown func close() async` — the scope-entry thunk's teardown
        // closure calls it against the construction local (M5.4.5, consistent with the graph's teardown).
        // The borrowed app singleton is excluded (it is torn down at app scope, not per request).
        let subject = DiscoveredScopeBoundType(
            typeName: "SessionController",
            typeKind: "struct",
            genericParameterNames: [],
            dependencies: [
                DependencyParameter(name: "seed", type: "RequestSeed", kind: .injectInitParameter, location: mockLocation("S.swift")),
                DependencyParameter(name: "connection", type: "RequestConn", kind: .injectInitParameter, location: mockLocation("S.swift")),
            ],
            location: mockLocation("S.swift"),
            scopeKey: ScopeKey(seed: "RequestSeed"),
            originModule: testModule
        )
        let proxy = contributorProxyBinding(
            for: subject,
            key: "WireMVCKeys.routeContributors",
            prefix: "_WireRouteContributor_",
            proxyScope: .singleton
        )
        let close = TeardownAction(
            kind: .member(methodName: "close", isAsync: true, isThrowing: false),
            location: mockLocation("RequestConn.swift")
        )
        let scope = SeedScopeEmission(
            seedTypeExpression: "RequestSeed",
            identifierSuffix: "RequestSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "RequestSeed", accessPath: "requestSeed"),
                syntheticProvider(boundType: "TodoRepository", accessPath: "_wireGraph.todoRepository"),
                scopedSingleton(
                    "RequestConn",
                    seed: "RequestSeed",
                    dependencies: [(name: "seed", type: "RequestSeed")],
                    teardown: close
                ),
                scopedSingleton(
                    "SessionController",
                    seed: "RequestSeed",
                    dependencies: [(name: "seed", type: "RequestSeed"), (name: "connection", type: "RequestConn")]
                ),
            ],
            borrowedBindingPropertyNames: ["todoRepository"]
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [singleton("TodoRepository"), .scopeBound(proxy)],
            seedScopeOrders: [scope]
        )
        // The scoped resource is constructed, then torn down in the thunk's teardown closure.
        #expect(output.contains("let requestConn = RequestConn(seed: requestSeed)"))
        #expect(output.contains("let _wireScopeTeardown: @Sendable () async -> [any Error] = {"))
        #expect(output.contains("await requestConn.close()"))
        // The borrowed app singleton is not torn down here.
        #expect(!output.contains("todoRepository.close()"))
    }

    @Test func seedScopeBorrowingSingletonsExcludesThemFromStoredProperties() {
        // Singletons borrowed via the synthetic-borrow mechanism are
        // inlined at consumer call sites — emission substitutes the
        // borrow's access path (`_wireGraph.logger`, where `_wireGraph`
        // is the wire-graph parameter's internal name) into the
        // consumer's constructor args instead of declaring a local.
        // The scope struct doesn't store them either: the caller
        // already owns the wire graph. `borrowedBindingPropertyNames`
        // drives both the let-line skip and the stored-property filter.
        let scope = SeedScopeEmission(
            seedTypeExpression: "HBRequestSeed",
            identifierSuffix: "HBRequestSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "Logger", accessPath: "_wireGraph.logger"),
                syntheticProvider(boundType: "HBRequestSeed", accessPath: "hBRequestSeed"),
                scopedSingleton(
                    "RequestLogger",
                    seed: "HBRequestSeed",
                    dependencies: [
                        (name: "base", type: "Logger"),
                        (name: "seed", type: "HBRequestSeed"),
                    ]
                ),
            ],
            borrowedBindingPropertyNames: ["logger"]
        )
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph: Introspectable, Teardownable {
                let logger: Logger

                func introspect() -> WiringModel {
                    WiringModel(bindings: [
                        BindingInfo(type: "Logger", key: nil, kind: .singleton, scope: nil, dependencies: [], location: SourceLocation(module: "TestModule", file: "Logger.swift", line: 1)),
                    ])
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let logger = Logger()
                return _WireGraph(logger: logger)
            }

            internal struct _HBRequestSeedWireScope {
                let hBRequestSeed: HBRequestSeed
                let requestLogger: RequestLogger
            }

            private func _wireBootstrapHBRequestSeedScope(seed hBRequestSeed: HBRequestSeed, wireGraph _wireGraph: _WireGraph) async throws -> _HBRequestSeedWireScope {
                let requestLogger = RequestLogger(base: _wireGraph.logger, seed: hBRequestSeed)
                return _HBRequestSeedWireScope(hBRequestSeed: hBRequestSeed, requestLogger: requestLogger)
            }

            internal enum Wire {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
                static func bootstrapHBRequestSeedScope(seed: HBRequestSeed, wireGraph: _WireGraph) async throws -> _HBRequestSeedWireScope {
                    try await _wireBootstrapHBRequestSeedScope(seed: seed, wireGraph: wireGraph)
                }
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [singleton("Logger")],
            seedScopeOrders: [scope]
        )
        #expect(output == expected)
    }

    @Test func multipleSeedScopesEmitInSortedOrder() {
        // Two distinct seed types produce two `_<Suffix>WireScope`
        // structs, emitted in identifier-suffix sort order regardless
        // of insertion order. Deterministic output matters for stable
        // builds and diff readability.
        let request = SeedScopeEmission(
            seedTypeExpression: "RequestSeed",
            identifierSuffix: "RequestSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "RequestSeed", accessPath: "requestSeed")
            ],
            borrowedBindingPropertyNames: []
        )
        let job = SeedScopeEmission(
            seedTypeExpression: "JobSeed",
            identifierSuffix: "JobSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "JobSeed", accessPath: "jobSeed")
            ],
            borrowedBindingPropertyNames: []
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            // Insertion order intentionally non-alphabetical to confirm
            // sorted output.
            seedScopeOrders: [request, job]
        )
        // JobSeed sorts before RequestSeed alphabetically; chop the
        // output at each struct's marker and assert the remainder
        // shrinks from the JobSeed split (later marker still present)
        // to the RequestSeed split (last struct in the output).
        let jobMarker = "_JobSeedWireScope"
        let requestMarker = "_RequestSeedWireScope"
        #expect(output.contains(jobMarker))
        #expect(output.contains(requestMarker))
        let afterJobSplit = output.split(separator: jobMarker).last.map(String.init) ?? ""
        let afterRequestSplit = output.split(separator: requestMarker).last.map(String.init) ?? ""
        // After splitting on JobSeed, the remainder still contains the
        // RequestSeed marker (RequestSeed comes later). After splitting
        // on RequestSeed, the remainder does not contain JobSeed (no
        // later occurrences).
        #expect(afterJobSplit.contains(requestMarker))
        #expect(!afterRequestSplit.contains(jobMarker))
    }

    @Test func seedScopeGenericSeedTypeProducesSanitisedSuffix() {
        // A seed expression like `TenantSeed<String>` sanitises to
        // `TenantSeedOfString` for the struct name, mirroring the
        // generic-instantiation convention used for binding property
        // names elsewhere in emission.
        let scope = SeedScopeEmission(
            seedTypeExpression: "TenantSeed<String>",
            identifierSuffix: sanitizeIdentifier("TenantSeed<String>"),
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(
                    boundType: "TenantSeed<String>",
                    accessPath: "tenantSeedOfString"
                )
            ],
            borrowedBindingPropertyNames: []
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            seedScopeOrders: [scope]
        )
        #expect(output.contains("internal struct _TenantSeedOfStringWireScope {"))
        #expect(
            output.contains(
                "static func bootstrapTenantSeedOfStringScope(seed: TenantSeed<String>, wireGraph: _WireGraph) async throws"
            )
        )
        // The private function uses `seed tenantSeedOfString:` and
        // `wireGraph _WireGraph:` — external and internal labels are
        // both derived from the parameter type via the standard
        // property-name rule.
        #expect(
            output.contains(
                "private func _wireBootstrapTenantSeedOfStringScope(seed tenantSeedOfString: TenantSeed<String>, wireGraph _wireGraph: _WireGraph)"
            )
        )
    }

    @Test func containerScopeEmissionTargetsContainerWireGraphAsParent() {
        // A seeded scope inside a `@Container` emits a
        // `_<Container>_<Seed>WireScope` struct whose bootstrap
        // signature targets the container's graph as the wire-graph
        // parameter (`_TestContainerWireGraph` instead of `_WireGraph`).
        // The parameter's external label is type-anchored
        // (`_TestContainerWireGraph` → `testContainerWireGraph:` after
        // stripping the leading underscore and lowerCamel-ing); the
        // internal name carries the underscore back (`_testContainerWireGraph`)
        // so it stays distinct from any user binding whose property
        // name might resolve to `testContainerWireGraph`. Borrows
        // inline against `_testContainerWireGraph.<prop>` at consumer
        // call sites.
        let scope = SeedScopeEmission(
            seedTypeExpression: "HBRequestSeed",
            identifierSuffix: "TestContainer_HBRequestSeed",
            parentGraphType: "_TestContainerWireGraph",
            topologicalOrder: [
                syntheticProvider(
                    boundType: "Logger",
                    accessPath: "_testContainerWireGraph.logger"
                ),
                syntheticProvider(boundType: "HBRequestSeed", accessPath: "hBRequestSeed"),
                scopedSingleton(
                    "RequestLogger",
                    seed: "HBRequestSeed",
                    dependencies: [
                        (name: "base", type: "Logger"),
                        (name: "seed", type: "HBRequestSeed"),
                    ]
                ),
            ],
            borrowedBindingPropertyNames: ["logger"]
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            seedScopeOrders: [scope]
        )
        #expect(output.contains("internal struct _TestContainer_HBRequestSeedWireScope {"))
        #expect(
            output.contains(
                "static func bootstrapTestContainer_HBRequestSeedScope(seed: HBRequestSeed, testContainerWireGraph: _TestContainerWireGraph) async throws"
            )
        )
        #expect(
            output.contains(
                "private func _wireBootstrapTestContainer_HBRequestSeedScope(seed hBRequestSeed: HBRequestSeed, testContainerWireGraph _testContainerWireGraph: _TestContainerWireGraph)"
            )
        )
        // Borrow inlined at the consumer's arg site against the
        // container's graph, not `_WireGraph`.
        #expect(output.contains("RequestLogger(base: _testContainerWireGraph.logger, seed: hBRequestSeed)"))
    }

    @Test func seedScopeNamesOpaqueParentGraphWithItsLiftedParameters() {
        // When the parent graph carries an `@Singleton(as:)` opaque binding it becomes generic
        // (`_WireGraph<T0: TodoRepository>`), so the seed scope's `wireGraph:` parameter must
        // name the opaque-erased form `_WireGraph<some TodoRepository>`. A bare `_WireGraph`
        // reference here is a `reference to generic type '_WireGraph' requires arguments` error.
        let opaqueRepo = DiscoveredBinding.scopeBound(
            DiscoveredScopeBoundType(
                typeName: "SQLiteTodoRepository",
                typeKind: "class",
                genericParameterNames: [],
                explicitIdentity: "TodoRepository",
                dependencies: [],
                location: mockLocation("Repo.swift"),
                originModule: testModule
            )
        )
        let scope = SeedScopeEmission(
            seedTypeExpression: "HBRequestSeed",
            identifierSuffix: "HBRequestSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "HBRequestSeed", accessPath: "hBRequestSeed"),
                scopedSingleton(
                    "RequestLogger",
                    seed: "HBRequestSeed",
                    dependencies: [(name: "seed", type: "HBRequestSeed")]
                ),
            ],
            borrowedBindingPropertyNames: []
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [opaqueRepo],
            seedScopeOrders: [scope]
        )
        // The parent graph is generic over the lifted parameter…
        #expect(output.contains("internal struct _WireGraph<T0: TodoRepository>"))
        // …so both the bootstrap function and the façade name the opaque-erased parent type.
        #expect(
            output.contains(
                "wireGraph _wireGraph: _WireGraph<some TodoRepository>) async throws -> _HBRequestSeedWireScope"
            )
        )
        #expect(
            output.contains(
                "static func bootstrapHBRequestSeedScope(seed: HBRequestSeed, wireGraph: _WireGraph<some TodoRepository>)"
            )
        )
        // The regression: no bare `_WireGraph` parameter reference survives in the seed plumbing.
        #expect(!output.contains("wireGraph _wireGraph: _WireGraph)"))
        #expect(!output.contains("wireGraph: _WireGraph)"))
    }
}
