import Testing

@testable import WireGenCore

@Suite("SeedScopeEmission")
struct SeedScopeEmissionTests {
    // MARK: - Helpers

    private func singleton(_ name: String) -> DiscoveredBinding {
        .scopeBound(
            DiscoveredScopeBoundType(
                typeName: name,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: [],
                location: mockLocation("\(name).swift"),
                originModule: testModule
            )
        )
    }

    private func scopedSingleton(
        _ name: String,
        seed: String,
        dependencies: [(name: String?, type: String)] = []
    ) -> DiscoveredBinding {
        let deps = dependencies.map {
            DependencyParameter(
                name: $0.name,
                type: $0.type,
                kind: .injectInitParameter,
                location: mockLocation("\(name).swift")
            )
        }
        return .scopeBound(
            DiscoveredScopeBoundType(
                typeName: name,
                typeKind: "struct",
                genericParameterNames: [],
                dependencies: deps,
                location: mockLocation("\(name).swift"),
                scopeKey: ScopeKey(seed: seed),
                originModule: testModule
            )
        )
    }

    private func syntheticProvider(boundType: String, accessPath: String) -> DiscoveredBinding {
        .provider(
            DiscoveredProvider(
                boundType: boundType,
                accessPath: accessPath,
                form: .property,
                dependencies: [],
                genericParameterNames: [],
                location: mockLocation("<synthetic>"),
                originModule: testModule
            )
        )
    }

    // MARK: - Tests

    @Test func seedScopeWithOnlySeedAliasingProducesScopeStruct() {
        // Smallest possible seed-scope graph: one `@Scoped` type whose
        // only dependency is the seed itself. The bootstrap aliases
        // `seed` to a local matching the seed's sanitised name; the
        // scope binding constructs against that local. No singleton
        // borrows are needed.
        let scope = SeedScopeEmission(
            seedTypeExpression: "HBRequestSeed",
            identifierSuffix: "HBRequestSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "HBRequestSeed", accessPath: "hBRequestSeed"),
                scopedSingleton(
                    "RequestLogger",
                    seed: "HBRequestSeed",
                    dependencies: [(name: "seed", type: "HBRequestSeed")]
                ),
            ],
            borrowedBindingPropertyNames: []
        )
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph {
                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                _WireGraph()
            }

            internal struct _HBRequestSeedWireScope {
                let hBRequestSeed: HBRequestSeed
                let requestLogger: RequestLogger

                static func bootstrap(seed: HBRequestSeed, wireGraph: _WireGraph) async throws -> _HBRequestSeedWireScope {
                    try await _wireBootstrapHBRequestSeedScope(seed: seed, wireGraph: wireGraph)
                }
            }

            private func _wireBootstrapHBRequestSeedScope(seed hBRequestSeed: HBRequestSeed, wireGraph _wireGraph: _WireGraph) async throws -> _HBRequestSeedWireScope {
                let requestLogger = RequestLogger(seed: hBRequestSeed)
                return _HBRequestSeedWireScope(hBRequestSeed: hBRequestSeed, requestLogger: requestLogger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            seedScopeOrders: [scope]
        )
        #expect(output == expected)
    }

    @Test func seedScopeBorrowingSingletonsExcludesThemFromStoredProperties() {
        // Singletons borrowed via the synthetic-borrow mechanism are
        // inlined at consumer call sites — emission substitutes the
        // borrow's access path (`_wireGraph.logger`, where `_wireGraph`
        // is the wire-graph parameter's internal name) into the
        // consumer's constructor args instead of declaring a local.
        // The scope struct doesn't store them either: the caller
        // already owns the wire graph. `borrowedBindingPropertyNames`
        // drives both the let-line skip and the stored-property filter.
        let scope = SeedScopeEmission(
            seedTypeExpression: "HBRequestSeed",
            identifierSuffix: "HBRequestSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "Logger", accessPath: "_wireGraph.logger"),
                syntheticProvider(boundType: "HBRequestSeed", accessPath: "hBRequestSeed"),
                scopedSingleton(
                    "RequestLogger",
                    seed: "HBRequestSeed",
                    dependencies: [
                        (name: "base", type: "Logger"),
                        (name: "seed", type: "HBRequestSeed"),
                    ]
                ),
            ],
            borrowedBindingPropertyNames: ["logger"]
        )
        let expected = """
            // Generated by WireGen — do not edit.

            internal struct _WireGraph {
                let logger: Logger

                static func bootstrap() async throws -> _WireGraph {
                    try await _wireBootstrap()
                }
            }

            private func _wireBootstrap() async throws -> _WireGraph {
                let logger = Logger()
                return _WireGraph(logger: logger)
            }

            internal struct _HBRequestSeedWireScope {
                let hBRequestSeed: HBRequestSeed
                let requestLogger: RequestLogger

                static func bootstrap(seed: HBRequestSeed, wireGraph: _WireGraph) async throws -> _HBRequestSeedWireScope {
                    try await _wireBootstrapHBRequestSeedScope(seed: seed, wireGraph: wireGraph)
                }
            }

            private func _wireBootstrapHBRequestSeedScope(seed hBRequestSeed: HBRequestSeed, wireGraph _wireGraph: _WireGraph) async throws -> _HBRequestSeedWireScope {
                let requestLogger = RequestLogger(base: _wireGraph.logger, seed: hBRequestSeed)
                return _HBRequestSeedWireScope(hBRequestSeed: hBRequestSeed, requestLogger: requestLogger)
            }

            """
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [singleton("Logger")],
            seedScopeOrders: [scope]
        )
        #expect(output == expected)
    }

    @Test func multipleSeedScopesEmitInSortedOrder() {
        // Two distinct seed types produce two `_<Suffix>WireScope`
        // structs, emitted in identifier-suffix sort order regardless
        // of insertion order. Deterministic output matters for stable
        // builds and diff readability.
        let request = SeedScopeEmission(
            seedTypeExpression: "RequestSeed",
            identifierSuffix: "RequestSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "RequestSeed", accessPath: "requestSeed")
            ],
            borrowedBindingPropertyNames: []
        )
        let job = SeedScopeEmission(
            seedTypeExpression: "JobSeed",
            identifierSuffix: "JobSeed",
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(boundType: "JobSeed", accessPath: "jobSeed")
            ],
            borrowedBindingPropertyNames: []
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            // Insertion order intentionally non-alphabetical to confirm
            // sorted output.
            seedScopeOrders: [request, job]
        )
        // JobSeed sorts before RequestSeed alphabetically; chop the
        // output at each struct's marker and assert the remainder
        // shrinks from the JobSeed split (later marker still present)
        // to the RequestSeed split (last struct in the output).
        let jobMarker = "_JobSeedWireScope"
        let requestMarker = "_RequestSeedWireScope"
        #expect(output.contains(jobMarker))
        #expect(output.contains(requestMarker))
        let afterJobSplit = output.split(separator: jobMarker).last.map(String.init) ?? ""
        let afterRequestSplit = output.split(separator: requestMarker).last.map(String.init) ?? ""
        // After splitting on JobSeed, the remainder still contains the
        // RequestSeed marker (RequestSeed comes later). After splitting
        // on RequestSeed, the remainder does not contain JobSeed (no
        // later occurrences).
        #expect(afterJobSplit.contains(requestMarker))
        #expect(!afterRequestSplit.contains(jobMarker))
    }

    @Test func seedScopeGenericSeedTypeProducesSanitisedSuffix() {
        // A seed expression like `TenantSeed<String>` sanitises to
        // `TenantSeedOfString` for the struct name, mirroring the
        // generic-instantiation convention used for binding property
        // names elsewhere in emission.
        let scope = SeedScopeEmission(
            seedTypeExpression: "TenantSeed<String>",
            identifierSuffix: sanitizeIdentifier("TenantSeed<String>"),
            parentGraphType: "_WireGraph",
            topologicalOrder: [
                syntheticProvider(
                    boundType: "TenantSeed<String>",
                    accessPath: "tenantSeedOfString"
                )
            ],
            borrowedBindingPropertyNames: []
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            seedScopeOrders: [scope]
        )
        #expect(output.contains("internal struct _TenantSeedOfStringWireScope {"))
        #expect(
            output.contains(
                "static func bootstrap(seed: TenantSeed<String>, wireGraph: _WireGraph) async throws"
            )
        )
        // The private function uses `seed tenantSeedOfString:` and
        // `wireGraph _WireGraph:` — external and internal labels are
        // both derived from the parameter type via the standard
        // property-name rule.
        #expect(
            output.contains(
                "private func _wireBootstrapTenantSeedOfStringScope(seed tenantSeedOfString: TenantSeed<String>, wireGraph _wireGraph: _WireGraph)"
            )
        )
    }

    @Test func containerScopeEmissionTargetsContainerWireGraphAsParent() {
        // A seeded scope inside a `@Container` emits a
        // `_<Container>_<Seed>WireScope` struct whose bootstrap
        // signature targets the container's graph as the wire-graph
        // parameter (`_TestContainerWireGraph` instead of `_WireGraph`).
        // The parameter's external label is type-anchored
        // (`_TestContainerWireGraph` → `testContainerWireGraph:` after
        // stripping the leading underscore and lowerCamel-ing); the
        // internal name carries the underscore back (`_testContainerWireGraph`)
        // so it stays distinct from any user binding whose property
        // name might resolve to `testContainerWireGraph`. Borrows
        // inline against `_testContainerWireGraph.<prop>` at consumer
        // call sites.
        let scope = SeedScopeEmission(
            seedTypeExpression: "HBRequestSeed",
            identifierSuffix: "TestContainer_HBRequestSeed",
            parentGraphType: "_TestContainerWireGraph",
            topologicalOrder: [
                syntheticProvider(
                    boundType: "Logger",
                    accessPath: "_testContainerWireGraph.logger"
                ),
                syntheticProvider(boundType: "HBRequestSeed", accessPath: "hBRequestSeed"),
                scopedSingleton(
                    "RequestLogger",
                    seed: "HBRequestSeed",
                    dependencies: [
                        (name: "base", type: "Logger"),
                        (name: "seed", type: "HBRequestSeed"),
                    ]
                ),
            ],
            borrowedBindingPropertyNames: ["logger"]
        )
        let output = renderWireGraph(
            imports: [],
            topologicalOrder: [],
            seedScopeOrders: [scope]
        )
        #expect(output.contains("internal struct _TestContainer_HBRequestSeedWireScope {"))
        #expect(
            output.contains(
                "static func bootstrap(seed: HBRequestSeed, testContainerWireGraph: _TestContainerWireGraph) async throws"
            )
        )
        #expect(
            output.contains(
                "private func _wireBootstrapTestContainer_HBRequestSeedScope(seed hBRequestSeed: HBRequestSeed, testContainerWireGraph _testContainerWireGraph: _TestContainerWireGraph)"
            )
        )
        // Borrow inlined at the consumer's arg site against the
        // container's graph, not `_WireGraph`.
        #expect(output.contains("RequestLogger(base: _testContainerWireGraph.logger, seed: hBRequestSeed)"))
    }
}
