import Wire
import WireHarnessLibrary

/// A consumer `@Singleton` that injects the external library's bindings
/// across the package boundary — both the unkeyed `@Singleton` and the
/// keyed `@Provides(ExternalService.primary)`.
@Singleton(allowUnused: true)
struct App {
    @Inject var service: ExternalService
    @Inject(ExternalService.primary) var primary: ExternalService
}

// `_WireGraph` is generated by WireBuildPlugin running on this target; it
// composes the consumer's own bindings with the activated external
// library's. Bootstrapping and reading the values proves the external
// `.product` activation path (7d), the foreign `import` (7c), and
// cross-module key resolution (7a/7f) end-to-end across a package boundary.
let graph = try await _WireGraph.bootstrap()
precondition(graph.app.service.name == "external", "unkeyed external binding did not compose")
precondition(graph.app.primary.name == "external", "keyed external binding did not compose")
print("OK: composed unkeyed + keyed ExternalService from external package")
