import Foundation
import WireGenCore

/// `WireGen` — code-generation executable invoked by the Wire build plugin.
///
/// Sitting 3: thin CLI wrapper over `WireGenCore`. Discovers
/// `@Singleton` types in the input source files, builds a dependency
/// graph, runs topological sort with cycle detection and missing-binding
/// detection, and prints the discovery report plus either the
/// topological order (success) or validation errors (failure). Exits
/// non-zero on validation errors.
///
/// Real `_WireGraph.swift` emission lands in sitting 4; until then, the
/// placeholder stub is still written to the output path so the build
/// plugin's output-file contract holds.
///
/// CLI shape:
///
///     WireGen <output-path> [source-files...]
@main
struct WireGen {
    static func main() throws {
        let arguments = CommandLine.arguments

        guard arguments.count >= 2 else {
            FileHandle.standardError.write(
                Data(
                    "error: WireGen requires at least an output path argument.\n".utf8
                )
            )
            FileHandle.standardError.write(
                Data("usage: WireGen <output-path> [source-files...]\n".utf8)
            )
            exit(1)
        }

        let outputPath = arguments[1]
        let sourcePaths = Array(arguments.dropFirst(2))

        // 1. Discover @Singleton types across input sources.
        var perFileDiscovered: [(path: String, items: [DiscoveredSingleton])] = []
        for path in sourcePaths {
            let url = URL(fileURLWithPath: path)
            let source: String
            do {
                source = try String(contentsOf: url, encoding: .utf8)
            } catch {
                FileHandle.standardError.write(
                    Data("error: failed to read \(path): \(error)\n".utf8)
                )
                exit(1)
            }
            let items = discoverSingletons(in: source, sourcePath: path)
            perFileDiscovered.append((path: path, items: items))
        }
        print(renderDiscoveryReport(perFile: perFileDiscovered))

        // 2. Build the dependency graph and run topo sort + validation.
        let allDiscovered = perFileDiscovered.flatMap { $0.items }
        let graphResult = buildDependencyGraph(from: allDiscovered)

        // 3. Print skipped (generic) singletons if any — informational.
        let skippedReport = renderSkipped(graphResult.skipped)
        if !skippedReport.isEmpty {
            print("")
            print(skippedReport)
        }

        // 4. Validation errors → stderr + non-zero exit.
        if graphResult.hasErrors {
            FileHandle.standardError.write(Data("\n".utf8))
            FileHandle.standardError.write(
                Data(renderValidationErrors(graphResult).utf8)
            )
            FileHandle.standardError.write(Data("\n".utf8))
            exit(1)
        }

        // 5. Success — print topological order.
        print("")
        print(renderTopologicalOrder(graphResult.topologicalOrder))

        // 6. Write the placeholder _WireGraph.swift. Real emission lands in
        // sitting 4 — the build plugin still wants an output file regardless
        // so the rest of the pipeline can be wired up.
        let stubContents = """
            // Generated by WireGen — placeholder produced by the sitting 3 scaffold.
            //
            // The real graph aggregation, validation, and code emission lands in
            // sitting 4. This stub exists so the build plugin's "produced an
            // output file" contract is satisfied and the rest of the pipeline
            // can be wired up and exercised end-to-end.

            internal struct _WireGraph {
                static func bootstrap() async throws -> _WireGraph {
                    _WireGraph()
                }
            }

            """

        try stubContents.write(toFile: outputPath, atomically: true, encoding: .utf8)
        print("wrote stub to \(outputPath)")
    }
}
