import Foundation

/// `WireGen` — code-generation executable invoked by the Wire build plugin.
///
/// Sitting 1 scaffold: parses command-line arguments and writes a stub
/// `_WireGraph.swift` to the requested output path. The stub satisfies the
/// build plugin's "produced an output file" contract so the rest of the
/// pipeline can be wired up and tested. Real graph aggregation,
/// validation, and code emission land in sittings 2–4.
///
/// CLI shape:
///
///     WireGen <output-path> [source-files...]
///
/// - `<output-path>` is the absolute path of the `.swift` file to generate.
/// - `[source-files...]` is the list of `.swift` files in the consumer
///   target the plugin wants WireGen to scan. Ignored at sitting 1.
@main
struct WireGen {
    static func main() throws {
        let arguments = CommandLine.arguments

        guard arguments.count >= 2 else {
            FileHandle.standardError.write(
                Data(
                    "error: WireGen requires at least an output path argument.\n"
                        .utf8
                )
            )
            FileHandle.standardError.write(
                Data("usage: WireGen <output-path> [source-files...]\n".utf8)
            )
            exit(1)
        }

        let outputPath = arguments[1]
        let sourcePaths = Array(arguments.dropFirst(2))

        print("WireGen sitting 1 scaffold")
        print("output path: \(outputPath)")
        print("source paths (\(sourcePaths.count)):")
        for path in sourcePaths {
            print("  - \(path)")
        }

        let stubContents = """
            // Generated by WireGen — placeholder produced by the sitting 1 scaffold.
            //
            // The real graph aggregation, validation, and code emission lands in
            // sittings 2–4. This stub exists so the build plugin's "produced an
            // output file" contract is satisfied and the rest of the pipeline
            // can be wired up and exercised end-to-end.

            internal struct _WireGraph {
                static func bootstrap() async throws -> _WireGraph {
                    _WireGraph()
                }
            }

            """

        try stubContents.write(toFile: outputPath, atomically: true, encoding: .utf8)
        print("wrote stub to \(outputPath)")
    }
}
