import Foundation
import SwiftParser
import SwiftSyntax

/// `WireGen` — code-generation executable invoked by the Wire build plugin.
///
/// Sitting 2: walks the input source files with SwiftSyntax, finds every
/// `@Singleton`-annotated type, and prints a discovery report listing
/// each type's dependencies (whether declared via an `@Inject`-marked
/// init or via `@Inject` stored properties). Validation across the
/// discovered set, graph construction, and real `_WireGraph.swift`
/// emission land in sittings 3–4. Until then the placeholder
/// `_WireGraph` from sitting 1 is still written to the output path so
/// the build plugin's output-file contract is satisfied.
///
/// CLI shape:
///
///     WireGen <output-path> [source-files...]
@main
struct WireGen {
    static func main() throws {
        let arguments = CommandLine.arguments

        guard arguments.count >= 2 else {
            FileHandle.standardError.write(
                Data(
                    "error: WireGen requires at least an output path argument.\n".utf8
                )
            )
            FileHandle.standardError.write(
                Data("usage: WireGen <output-path> [source-files...]\n".utf8)
            )
            exit(1)
        }

        let outputPath = arguments[1]
        let sourcePaths = Array(arguments.dropFirst(2))

        var perFileDiscovered: [(path: String, items: [DiscoveredSingleton])] = []
        for path in sourcePaths {
            let url = URL(fileURLWithPath: path)
            let source: String
            do {
                source = try String(contentsOf: url, encoding: .utf8)
            } catch {
                FileHandle.standardError.write(
                    Data("error: failed to read \(path): \(error)\n".utf8)
                )
                exit(1)
            }

            let syntaxTree = Parser.parse(source: source)
            let visitor = SingletonDiscovery(sourcePath: path)
            visitor.walk(syntaxTree)
            perFileDiscovered.append((path: path, items: visitor.discovered))
        }

        print(renderDiscoveryReport(perFile: perFileDiscovered))

        let stubContents = """
            // Generated by WireGen — placeholder produced by the sitting 2 scaffold.
            //
            // The real graph aggregation, validation, and code emission lands in
            // sittings 3–4. This stub exists so the build plugin's "produced an
            // output file" contract is satisfied and the rest of the pipeline
            // can be wired up and exercised end-to-end.

            internal struct _WireGraph {
                static func bootstrap() async throws -> _WireGraph {
                    _WireGraph()
                }
            }

            """

        try stubContents.write(toFile: outputPath, atomically: true, encoding: .utf8)
        print("wrote stub to \(outputPath)")
    }
}

// MARK: - Discovery model

/// One `@Singleton`-annotated type found in a source file, with the
/// dependency declaration extracted from either an `@Inject`-marked init
/// or from `@Inject` stored properties on the type.
struct DiscoveredSingleton {
    let typeName: String
    let typeKind: String
    let genericParameterNames: [String]
    let dependencies: [DependencyParameter]
    let sourcePath: String
}

/// One dependency that the synthesised (or user-marked) initialiser takes
/// — i.e. one parameter Wire must resolve from the graph at construction
/// time.
struct DependencyParameter {
    let name: String
    let type: String
    let kind: DependencyKind
}

enum DependencyKind {
    case injectProperty
    case injectInitParameter
}

// MARK: - Discovery visitor

/// Walks a parsed source tree looking for `@Singleton`-annotated types.
/// For each, captures the type's name, generic parameter list, and
/// dependencies in declaration-order.
///
/// Dependency source preference matches `SingletonMacro`'s rule:
/// 1. If the type has an `@Inject`-marked initialiser, dependencies come
///    from that initialiser's parameter list.
/// 2. Otherwise, dependencies come from `@Inject`-marked stored
///    properties in declaration order.
///
/// Validation (multiple `@Inject` inits, mixing init+property `@Inject`,
/// etc.) is the macro's job and fires during the consumer's compilation.
/// WireGen is downstream of that and assumes the inputs are well-formed
/// enough to discover; mismatches surface at construction-time codegen
/// in sittings 3–4.
final class SingletonDiscovery: SyntaxVisitor {
    var discovered: [DiscoveredSingleton] = []
    private let sourcePath: String

    init(sourcePath: String) {
        self.sourcePath = sourcePath
        super.init(viewMode: .sourceAccurate)
    }

    override func visit(_ node: StructDeclSyntax) -> SyntaxVisitorContinueKind {
        process(
            typeKind: "struct",
            name: node.name.text,
            generics: node.genericParameterClause,
            attributes: node.attributes,
            members: node.memberBlock.members
        )
        return .visitChildren
    }

    override func visit(_ node: ClassDeclSyntax) -> SyntaxVisitorContinueKind {
        process(
            typeKind: "class",
            name: node.name.text,
            generics: node.genericParameterClause,
            attributes: node.attributes,
            members: node.memberBlock.members
        )
        return .visitChildren
    }

    override func visit(_ node: ActorDeclSyntax) -> SyntaxVisitorContinueKind {
        process(
            typeKind: "actor",
            name: node.name.text,
            generics: node.genericParameterClause,
            attributes: node.attributes,
            members: node.memberBlock.members
        )
        return .visitChildren
    }

    private func process(
        typeKind: String,
        name: String,
        generics: GenericParameterClauseSyntax?,
        attributes: AttributeListSyntax,
        members: MemberBlockItemListSyntax
    ) {
        guard hasAttribute(attributes, named: "Singleton") else { return }
        let genericParameterNames = generics?.parameters.map { $0.name.text } ?? []
        let dependencies = extractDependencies(from: members)
        discovered.append(
            DiscoveredSingleton(
                typeName: name,
                typeKind: typeKind,
                genericParameterNames: genericParameterNames,
                dependencies: dependencies,
                sourcePath: sourcePath
            )
        )
    }

    private func extractDependencies(
        from members: MemberBlockItemListSyntax
    ) -> [DependencyParameter] {
        // Single pass: collect both candidate dependency lists. Choose at
        // the end based on the same priority rule as `SingletonMacro`:
        // an `@Inject`-marked init's parameter list takes precedence over
        // `@Inject` properties.
        var injectInitDependencies: [DependencyParameter]?
        var propertyDependencies: [DependencyParameter] = []

        for member in members {
            if let initDecl = member.decl.as(InitializerDeclSyntax.self) {
                if hasAttribute(initDecl.attributes, named: "Inject") {
                    injectInitDependencies = initDecl.signature.parameterClause.parameters.map {
                        parameter in
                        DependencyParameter(
                            name: parameterName(parameter),
                            type: parameter.type.trimmedDescription,
                            kind: .injectInitParameter
                        )
                    }
                }
                continue
            }

            guard let varDecl = member.decl.as(VariableDeclSyntax.self) else { continue }
            guard hasAttribute(varDecl.attributes, named: "Inject") else { continue }
            for binding in varDecl.bindings {
                guard let pattern = binding.pattern.as(IdentifierPatternSyntax.self) else { continue }
                guard let typeAnnotation = binding.typeAnnotation else { continue }
                propertyDependencies.append(
                    DependencyParameter(
                        name: pattern.identifier.text,
                        type: typeAnnotation.type.trimmedDescription,
                        kind: .injectProperty
                    )
                )
            }
        }

        return injectInitDependencies ?? propertyDependencies
    }

    /// The parameter's "internal" name — the one used inside the function
    /// body. For `init(_ a: Int)` that's `a` (secondName). For
    /// `init(label internal: Int)` that's `internal`. For `init(a: Int)`
    /// it's `a` (firstName, since secondName is nil).
    private func parameterName(_ parameter: FunctionParameterSyntax) -> String {
        if parameter.firstName.tokenKind == .wildcard {
            return parameter.secondName?.text ?? "_"
        }
        return parameter.secondName?.text ?? parameter.firstName.text
    }

    private func hasAttribute(
        _ attributes: AttributeListSyntax,
        named name: String
    ) -> Bool {
        attributes.contains { element in
            guard let attribute = element.as(AttributeSyntax.self) else { return false }
            return attribute.attributeName.trimmedDescription == name
        }
    }
}

// MARK: - Discovery report

/// Produce a human-readable summary of what `SingletonDiscovery` found
/// across all the input source files. Files with no `@Singleton` types
/// are omitted to keep the report scannable.
func renderDiscoveryReport(
    perFile: [(path: String, items: [DiscoveredSingleton])]
) -> String {
    var lines: [String] = []
    lines.append("WireGen sitting 2: discovery report")
    lines.append("")

    var totalCount = 0
    let sourceFileCount = perFile.count

    for (path, items) in perFile {
        guard !items.isEmpty else { continue }
        lines.append("\(path):")
        for item in items {
            totalCount += 1
            let generics =
                item.genericParameterNames.isEmpty
                ? ""
                : "<\(item.genericParameterNames.joined(separator: ", "))>"
            lines.append("  @Singleton \(item.typeKind) \(item.typeName)\(generics)")
            if item.dependencies.isEmpty {
                lines.append("    (no dependencies)")
            } else {
                for dep in item.dependencies {
                    let kindLabel: String
                    switch dep.kind {
                    case .injectProperty: kindLabel = "@Inject property"
                    case .injectInitParameter: kindLabel = "@Inject init parameter"
                    }
                    lines.append("    \(dep.name): \(dep.type)   (\(kindLabel))")
                }
            }
        }
        lines.append("")
    }

    lines.append(
        "discovered \(totalCount) @Singleton type(s) across \(sourceFileCount) source file(s)"
    )

    return lines.joined(separator: "\n")
}
