/// Render the `_WireGraph.swift` source the build plugin writes
/// alongside the consumer target. The generated struct has one stored
/// property per binding (named by `lowerCamelCased(sanitize(boundType))`)
/// and a static `bootstrap() async throws -> _WireGraph` that
/// constructs each binding in dependency order.
///
/// All references to user-supplied symbols on the RHS of the
/// constructed locals are module-qualified — `<moduleName>.SomeType(...)`,
/// `<moduleName>.someProvider`, `<moduleName>.Config.someStaticProvider`.
/// Module qualification removes the recursive-shadow case when a
/// `@Provides let X` shares its declaration name with the lowered type
/// name, and aligns with the multi-module composition model planned
/// for iteration 7 (each binding will eventually carry its own
/// origin-module qualifier).
///
/// `bootstrap` is declared `async throws` regardless of whether the
/// current set of bindings actually have async/throws inits. M6's
/// lifecycle work makes async/throws constructor injection a
/// first-class option, and locking the signature in now means later
/// migrations don't ripple through every consumer's `try await
/// _WireGraph.bootstrap()` call site. Swift accepts an `async throws`
/// function body that doesn't actually use those capabilities.
package func renderWireGraph(
    moduleName: String,
    topologicalOrder: [DiscoveredBinding]
) -> String {
    var lines: [String] = []

    lines.append("// Generated by WireGen — do not edit.")
    lines.append("")
    lines.append("internal struct _WireGraph: Sendable {")

    guard !topologicalOrder.isEmpty else {
        // Empty graph — no bindings to construct, but still emit a
        // valid struct so consumers can call `_WireGraph.bootstrap()`
        // without conditional compilation.
        lines.append("    static func bootstrap() async throws -> _WireGraph {")
        lines.append("        _WireGraph()")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    // One stored property per binding.
    for binding in topologicalOrder {
        let property = propertyName(for: binding)
        lines.append("    let \(property): \(binding.boundType)")
    }

    lines.append("")
    lines.append("    static func bootstrap() async throws -> _WireGraph {")

    // Construction body — each binding constructed in dependency order
    // so any value referenced as an argument is already in scope as a
    // previously-bound local.
    for binding in topologicalOrder {
        let local = propertyName(for: binding)
        let construction = constructionExpression(for: binding, moduleName: moduleName)
        lines.append("        let \(local) = \(construction)")
    }

    // Final return — the memberwise init takes one argument per stored
    // property, in declaration order. Argument value is the matching
    // local; argument label is the property name.
    let returnArgs = topologicalOrder.map { binding -> String in
        let name = propertyName(for: binding)
        return "\(name): \(name)"
    }.joined(separator: ", ")
    lines.append("        return _WireGraph(\(returnArgs))")

    lines.append("    }")
    lines.append("}")
    lines.append("")

    return lines.joined(separator: "\n")
}

/// The stored-property name on `_WireGraph` (and the local name in the
/// `bootstrap()` body) for a given binding. Type-derived: bindings are
/// identified by what they produce, not by their source-level
/// declaration name.
private func propertyName(for binding: DiscoveredBinding) -> String {
    lowerCamelCased(sanitizeIdentifier(binding.boundType))
}

/// The RHS expression that constructs a single binding inside
/// `bootstrap()`. All references to user-supplied symbols are
/// module-qualified.
private func constructionExpression(
    for binding: DiscoveredBinding,
    moduleName: String
) -> String {
    switch binding {
    case .singleton(let singleton):
        // The type is referenced verbatim — generic instantiations
        // (`Repository<TaskTable>`) keep their angle brackets at the
        // construction call site since Swift's syntax accepts that.
        let args = renderArguments(singleton.dependencies)
        return "\(moduleName).\(singleton.typeName)(\(args))"
    case .provider(let provider):
        switch provider.form {
        case .property:
            return "\(moduleName).\(provider.accessPath)"
        case .function:
            let args = renderArguments(provider.dependencies)
            return "\(moduleName).\(provider.accessPath)(\(args))"
        }
    }
}

/// Render a constructor's argument list. Each dependency is resolved
/// to the local-name for its bound type; the argument label comes from
/// the dependency's external label (or is omitted entirely for
/// wildcard labels).
private func renderArguments(_ dependencies: [DependencyParameter]) -> String {
    dependencies.map { dependency in
        let value = lowerCamelCased(sanitizeIdentifier(dependency.type))
        if let label = dependency.name {
            return "\(label): \(value)"
        }
        // Wildcard external label — the call site omits it entirely.
        return value
    }.joined(separator: ", ")
}

/// Strip a type expression down to a Swift-identifier-safe form for
/// use as a property/local name. Generic instantiations are encoded
/// with `Of` and `And` separators so distinct instantiations of the
/// same base type produce distinct names:
///
///     Repository<TaskTable>          → RepositoryOfTaskTable
///     Repository<Foo, Bar<Baz>>      → RepositoryOfFooAndBarOfBaz
///     any Logger                      → anyLogger
///
/// Other special-character cases (function types, optionals, tuples,
/// etc.) drop non-identifier characters; if a future user trips over
/// a collision (two distinct bound types that sanitize to the same
/// identifier), iteration 3's diagnostic pass will detect it. Until
/// then the recommended fix is a typealias.
private func sanitizeIdentifier(_ raw: String) -> String {
    var result = ""
    for char in raw {
        switch char {
        case "<":
            result += "Of"
        case ",":
            result += "And"
        default:
            if char.isLetter || char.isNumber || char == "_" {
                result.append(char)
            }
            // Everything else (whitespace, `>`, `?`, `!`, `[`, `]`,
            // `&`, `:`, `.`, `(`, `)`, `->`) is dropped silently.
        }
    }
    return result
}

/// Lowercase the first character only — `B` → `b`, `TaskRepository` →
/// `taskRepository`, `DynamoDBTaskRepository` → `dynamoDBTaskRepository`.
/// The simplest convention that produces unambiguous, distinct names.
/// More sophisticated acronym-aware casing (`URLSession` →
/// `urlSession`) can be added later if generated names look awkward
/// enough to bother with.
private func lowerCamelCased(_ name: String) -> String {
    guard let first = name.first else { return name }
    return first.lowercased() + name.dropFirst()
}
