/// Render the `_WireGraph.swift` source the build plugin writes
/// alongside the consumer target. The generated file contains:
///
/// - The `_WireGraph` struct with one stored property per binding,
///   named by `lowerCamelCased(sanitize(boundType))`.
/// - A static `bootstrap()` on the struct that delegates to a free
///   `_wireBootstrap()` at module scope.
/// - `_wireBootstrap()` performs the actual construction.
///
/// Why the delegation: from inside `_WireGraph.bootstrap()` (a static
/// method on the struct), Swift name lookup checks the struct's
/// members before module scope. A stored property named `appName`
/// shadows the user's module-scope `@Provides let appName` and the
/// compiler errors with "instance member cannot be used on type." The
/// free function at module scope has no enclosing type, so bare
/// references resolve straight to module scope, sidestepping the
/// shadow entirely.
///
/// Inside the free function, bare local names are safe even when they
/// equal a module-scope identifier — Swift's `let x = x` resolves the
/// RHS in the surrounding scope before the LHS is bound, so the local
/// shadows the outer correctly without self-reference issues.
///
/// `imports` are propagated verbatim from the input source files so
/// every type referenced by a binding stays in scope. The naive
/// "union all imports" approach can include unrelated imports that
/// happen to live in the same file as a binding — harmless for an
/// internal generated file. Iteration 7's cross-module work will
/// refine this if generated-file noise becomes a real complaint.
///
/// `bootstrap` is declared `async throws` regardless of whether the
/// current set of bindings actually have async/throws inits. M6's
/// lifecycle work makes async/throws constructor injection a
/// first-class option, and locking the signature in now means later
/// migrations don't ripple through every consumer's `try await
/// _WireGraph.bootstrap()` call site. Swift accepts an `async throws`
/// function body that doesn't actually use those capabilities.
package func renderWireGraph(
    imports: [String],
    topologicalOrder: [DiscoveredBinding],
    containerTopologicalOrders: [String: [DiscoveredBinding]] = [:],
    seedScopeOrders: [SeedScopeEmission] = []
) -> String {
    var lines: [String] = []

    lines.append("// Generated by WireGen — do not edit.")

    // Imports — sorted and deduplicated for stability across runs.
    let sortedImports = Array(Set(imports)).sorted()
    if !sortedImports.isEmpty {
        lines.append("")
        for line in sortedImports {
            lines.append(line)
        }
    }

    // Default graph — always emitted, even when empty, so consumers
    // can call `_WireGraph.bootstrap()` unconditionally.
    appendStruct(
        structName: "_WireGraph",
        bootstrapFunction: "_wireBootstrap",
        topologicalOrder: topologicalOrder,
        into: &lines
    )

    // Per-container graphs — sorted by container name for deterministic
    // output. Each gets its own struct + free-function pair following
    // the same delegation pattern as the default. The free-function
    // discriminator is the container name so multiple containers don't
    // collide at module scope.
    for (containerName, order) in containerTopologicalOrders.sorted(by: { $0.key < $1.key }) {
        appendStruct(
            structName: "_\(containerName)WireGraph",
            bootstrapFunction: "_wireBootstrap\(containerName)",
            topologicalOrder: order,
            into: &lines
        )
    }

    // Per-seed scope graphs. Each emits a `_<Suffix>WireScope` struct
    // whose `bootstrap(seed:wireGraph:)` takes the externally-owned
    // seed value and the wire graph; the body aliases singleton
    // dependencies as locals via the synthetic-borrow bindings, then
    // constructs scope-bound bindings in topological order.
    for scope in seedScopeOrders.sorted(by: { $0.identifierSuffix < $1.identifierSuffix }) {
        appendSeedScopeStruct(scope: scope, into: &lines)
    }

    // Trailing newline at end of file. `appendStruct` is leading-blank
    // only, so the final struct's closing `}` doesn't end the file
    // without it.
    lines.append("")

    return lines.joined(separator: "\n")
}

/// Emission-side description of one per-seed scope graph. Mirrors
/// the orchestration result's relevant fields: the seed type
/// expression for the bootstrap seed-parameter type, the parent
/// graph type for the bootstrap wire-graph-parameter type
/// (`_WireGraph` for default-graph seeded scopes,
/// `_<Container>WireGraph` for container-scope ones), the identifier
/// suffix for the struct/function names, the topological order over
/// the combined graph, and the borrowed-binding property names so
/// the emitter knows which entries are singletons aliased from the
/// `wireGraph:` bootstrap parameter rather than constructed in place.
package struct SeedScopeEmission: Sendable {
    package let seedTypeExpression: String
    package let identifierSuffix: String
    package let parentGraphType: String
    package let topologicalOrder: [DiscoveredBinding]
    package let borrowedBindingPropertyNames: Set<String>

    package init(
        seedTypeExpression: String,
        identifierSuffix: String,
        parentGraphType: String,
        topologicalOrder: [DiscoveredBinding],
        borrowedBindingPropertyNames: Set<String>
    ) {
        self.seedTypeExpression = seedTypeExpression
        self.identifierSuffix = identifierSuffix
        self.parentGraphType = parentGraphType
        self.topologicalOrder = topologicalOrder
        self.borrowedBindingPropertyNames = borrowedBindingPropertyNames
    }
}

/// Emit one `_<Suffix>WireScope` struct + matching
/// `_wireBootstrap<Suffix>Scope` free function pair. The bootstrap
/// takes `(seed:, wireGraph:)` parameters. Borrowed singleton
/// bindings in the topological order are not declared as locals —
/// each borrow's `accessPath` (`<wireGraphLocal>.<prop>`) is inlined
/// at every consumer's arg site via the `resolvingLocal` hook on
/// `renderArguments`. The synthetic seed binding shadow-binds from
/// the parameter (`let X = X`) and is skipped via the
/// `local != construction` check. Net result: only scope-bound
/// bindings emit `let` lines, borrowed singletons appear at use
/// sites only, and unused borrows produce no output.
private func appendSeedScopeStruct(
    scope: SeedScopeEmission,
    into lines: inout [String]
) {
    let structName = "_\(scope.identifierSuffix)WireScope"
    let bootstrapFunction = "_wireBootstrap\(scope.identifierSuffix)Scope"
    let storedBindings = scope.topologicalOrder.filter {
        !scope.borrowedBindingPropertyNames.contains(propertyName(for: $0))
    }
    // Both bootstrap parameters use type-anchored labels rather than
    // role-anchored ones. The seed parameter keeps `seed:` as its
    // external label (the role here is fixed) but uses the seed
    // type's property-name form as its internal name. The wire-graph
    // parameter's external label is the parent-graph type's stripped
    // lowerCamel form (`wireGraph:` for `_WireGraph`,
    // `testContainerWireGraph:` for `_TestContainerWireGraph`) so
    // varying parent-graph types don't share the same label. Its
    // internal name is that external label prefixed with `_` so a
    // user binding whose property name resolves to `wireGraph` or
    // `testContainerWireGraph` can coexist without colliding on the
    // local-variable token inside the bootstrap body.
    let seedLocal = identifierName(forType: scope.seedTypeExpression, key: nil)
    let wireGraphExternal = wireGraphParameterLabel(forType: scope.parentGraphType)
    let wireGraphInternal = wireGraphParameterInternalName(forType: scope.parentGraphType)

    // Borrowed-singleton bindings get inlined at their consumers' arg
    // sites rather than declared as locals — every consumer in the
    // topo order resolves a borrow dep directly to the wire-graph
    // expression (`_WireGraph.logger`). The map's keys are borrow
    // property names; values are the substitution expressions read
    // straight off each borrow's `accessPath`. Unused borrows produce
    // no output: their let-lines are skipped and no consumer refers
    // to them, so they vanish from the emitted bootstrap.
    var borrowAccessPaths: [String: String] = [:]
    for binding in scope.topologicalOrder {
        let name = propertyName(for: binding)
        guard scope.borrowedBindingPropertyNames.contains(name),
            case .provider(let provider) = binding
        else { continue }
        borrowAccessPaths[name] = provider.accessPath
    }
    let resolveBorrow: (String) -> String? = { borrowAccessPaths[$0] }

    lines.append("")
    lines.append("internal struct \(structName): Sendable {")
    for binding in storedBindings {
        let property = propertyName(for: binding)
        lines.append("    let \(property): \(binding.boundTypeReference)")
    }
    if !storedBindings.isEmpty {
        lines.append("")
    }
    lines.append(
        "    static func bootstrap(seed: \(scope.seedTypeExpression), \(wireGraphExternal): \(scope.parentGraphType)) async throws -> \(structName) {"
    )
    lines.append(
        "        try await \(bootstrapFunction)(seed: seed, \(wireGraphExternal): \(wireGraphExternal))"
    )
    lines.append("    }")
    lines.append("}")

    lines.append("")
    lines.append(
        "private func \(bootstrapFunction)(seed \(seedLocal): \(scope.seedTypeExpression), \(wireGraphExternal) \(wireGraphInternal): \(scope.parentGraphType)) async throws -> \(structName) {"
    )

    if scope.topologicalOrder.isEmpty && storedBindings.isEmpty {
        lines.append("    \(structName)()")
        lines.append("}")
        return
    }

    for binding in scope.topologicalOrder {
        let local = propertyName(for: binding)
        // Borrows are inlined at their consumers' arg sites — no let-
        // line is needed (or wanted: unused borrows would otherwise
        // leave dead lines in the emitted bootstrap).
        if scope.borrowedBindingPropertyNames.contains(local) { continue }
        let construction = constructionExpression(for: binding, resolvingLocal: resolveBorrow)
        // Skip a redundant `let X = X` shadow: it happens when the
        // construction expression equals the local name, which inside
        // the seed bootstrap means the synthetic seed binding whose
        // access path is the parameter's internal name. Subsequent
        // bare references resolve to the parameter directly. The same
        // shadow on a module-scope provider would cross from module
        // scope into the function — that path stays in `appendStruct`
        // and isn't affected.
        guard local != construction else { continue }
        lines.append("    let \(local) = \(construction)")
    }

    let returnArgs = storedBindings.map { binding -> String in
        let name = propertyName(for: binding)
        return "\(name): \(name)"
    }.joined(separator: ", ")
    lines.append("    return \(structName)(\(returnArgs))")
    lines.append("}")
}

/// Emit one `_<Name>WireGraph` struct + matching `_wireBootstrap<Name>`
/// free function pair. Called once for the default graph and once per
/// container; the same shape carries through for both.
private func appendStruct(
    structName: String,
    bootstrapFunction: String,
    topologicalOrder: [DiscoveredBinding],
    into lines: inout [String]
) {
    lines.append("")
    lines.append("internal struct \(structName): Sendable {")

    // Stored properties — one per binding, type-derived name, no
    // prefix. Users access these as `graph.logger`, `graph.userService`.
    // The annotated type uses `boundTypeReference` so nested
    // `@Singleton`s inside a `@Container` qualify with the enclosing
    // path (`TestContainer.MockService`) — required because this
    // struct lives at module scope.
    for binding in topologicalOrder {
        let property = propertyName(for: binding)
        lines.append("    let \(property): \(binding.boundTypeReference)")
    }
    if !topologicalOrder.isEmpty {
        lines.append("")
    }

    lines.append("    static func bootstrap() async throws -> \(structName) {")
    lines.append("        try await \(bootstrapFunction)()")
    lines.append("    }")
    lines.append("}")

    // Free function at module scope — does the actual construction.
    // Module-scope context means bare `appName` / `logger` references
    // resolve cleanly to module-scope `@Provides` declarations,
    // bypassing the type-member shadow that would happen inside
    // the struct's `static func bootstrap()` directly.
    lines.append("")
    lines.append("private func \(bootstrapFunction)() async throws -> \(structName) {")

    guard !topologicalOrder.isEmpty else {
        // Empty graph — no bindings, return the empty memberwise init.
        lines.append("    \(structName)()")
        lines.append("}")
        return
    }

    // Construction body — bare local names. `let logger = logger`
    // works because Swift resolves the RHS in the outer scope before
    // binding the LHS local, so the local shadows cleanly.
    for binding in topologicalOrder {
        let local = propertyName(for: binding)
        let construction = constructionExpression(for: binding)
        lines.append("    let \(local) = \(construction)")
    }

    // Final return — memberwise init takes one argument per stored
    // property in declaration order. Label is the property name;
    // value is the matching local.
    let returnArgs = topologicalOrder.map { binding -> String in
        let name = propertyName(for: binding)
        return "\(name): \(name)"
    }.joined(separator: ", ")
    lines.append("    return \(structName)(\(returnArgs))")

    lines.append("}")
}

/// The stored-property name on `_WireGraph` and the local name in
/// `_wireBootstrap()` for a given binding. Type-derived: bindings are
/// identified by what they produce, not by their source-level
/// declaration name. Keyed bindings append a key-derived suffix so
/// that two providers of the same type with different keys don't
/// collide. See `identifierName(forType:key:)` for the rule.
private func propertyName(for binding: DiscoveredBinding) -> String {
    identifierName(forType: binding.boundType, key: binding.keyIdentifier)
}

/// The canonical local/property name for a `(boundType, key?)` pair.
/// Used for both binding declarations and dependency-resolution sites
/// so a keyed dependency points at the matching keyed binding's local.
/// Also called from `Graph.swift` to detect generated-accessor-name
/// collisions before codegen runs.
///
/// Rules:
/// - Unkeyed: `lowerCamel(sanitize(type))` — same as before keys
///   existed.
/// - Keyed: `lowerCamel(sanitize(type)) + "Keyed" + upperCamel(sanitize(key))`.
///
/// The `Keyed` infix is a sentinel segment matching the `Of`/`And`
/// separator pattern already used for generic instantiations
/// (`Repository<TaskTable>` → `RepositoryOfTaskTable`). It pushes the
/// collision space to "type names that literally contain the word
/// `Keyed` in the matching position," which doesn't happen in real
/// code. The verbose readout — `databaseKeyedDatabasePrimary` for
/// `(Database, "Database.primary")` — is a tradeoff: less ergonomic
/// than a stripped form (`databasePrimary`) but unambiguous, and the
/// keyed accessor is rarely the user's primary access path anyway
/// (keyed bindings usually live behind a consumer).
func identifierName(forType type: String, key: String?) -> String {
    let typeName = lowerCamelCased(sanitizeIdentifier(type))
    guard let key else { return typeName }
    let keySuffix = upperCamelCased(sanitizeKeyComponents(key))
    return typeName + "Keyed" + keySuffix
}

/// Sanitize a key expression for use inside an identifier. Dots are
/// treated as segment separators — the next letter is upper-cased,
/// the dot is dropped. Other non-identifier characters are dropped
/// silently, matching `sanitizeIdentifier`'s posture.
///
///     "primary"            → "primary"
///     "Database.primary"   → "DatabasePrimary"
///     "Module.Database.x"  → "ModuleDatabaseX"
private func sanitizeKeyComponents(_ raw: String) -> String {
    var result = ""
    var capitalizeNext = false
    for char in raw {
        if char == "." {
            capitalizeNext = true
            continue
        }
        guard char.isLetter || char.isNumber || char == "_" else { continue }
        if capitalizeNext {
            result += String(char).uppercased()
            capitalizeNext = false
        } else {
            result.append(char)
        }
    }
    return result
}

/// Uppercase the first character only — the symmetric counterpart to
/// `lowerCamelCased`. Used to make a key suffix capitalised so it
/// reads as a distinct word in the composed identifier
/// (`appName` + `Alternate` → `appNameAlternate`).
private func upperCamelCased(_ name: String) -> String {
    guard let first = name.first else { return name }
    return first.uppercased() + name.dropFirst()
}

/// The RHS expression that constructs a single binding inside
/// `bootstrap()`. Uses bare references — the consumer's source-file
/// imports are propagated to the generated file so user-supplied
/// symbols are in scope without qualification.
///
/// `resolvingLocal` is forwarded to `renderArguments` so per-graph
/// dependency substitutions (e.g., the seed-scope path inlining
/// borrowed singletons at use sites) flow through.
private func constructionExpression(
    for binding: DiscoveredBinding,
    resolvingLocal: ((String) -> String?)? = nil
) -> String {
    switch binding {
    case .scopeBound(let scopeBound):
        // Generic instantiations (`Repository<TaskTable>`) keep their
        // angle brackets at the call site since Swift's syntax accepts
        // that. `qualifiedTypeName` includes any enclosing-type
        // prefix (e.g. `TestContainer.MockService`) so a `@Singleton`
        // nested inside a `@Container` resolves correctly when called
        // from the module-scope `_wireBootstrap...` free function.
        let args = renderArguments(scopeBound.dependencies, resolvingLocal: resolvingLocal)
        let call = "\(scopeBound.qualifiedTypeName)(\(args))"
        return effectPrefix(
            isAsync: scopeBound.initIsAsync,
            isThrowing: scopeBound.initIsThrowing
        ) + call
    case .provider(let provider):
        let prefix = effectPrefix(
            isAsync: provider.isAsync,
            isThrowing: provider.isThrowing
        )
        switch provider.form {
        case .property:
            return prefix + provider.accessPath
        case .function:
            let args = renderArguments(provider.dependencies, resolvingLocal: resolvingLocal)
            // A specialised generic provider function carries the
            // concrete type arguments to splice in at the call site.
            // The bare call `makeRepo()` couldn't infer T from
            // context here (the local has no type annotation), so we
            // emit them explicitly: `makeRepo<DynamoDBTable>()`.
            // Non-specialised provider functions have an empty
            // arguments list and call through as `accessPath(args)`.
            if !provider.concreteGenericArguments.isEmpty {
                let generics =
                    provider.concreteGenericArguments
                    .joined(separator: ", ")
                return "\(prefix)\(provider.accessPath)<\(generics)>(\(args))"
            }
            return "\(prefix)\(provider.accessPath)(\(args))"
        }
    }
}

/// Combine `isAsync` / `isThrowing` into the call-site prefix Swift
/// expects on an effectful call expression. Returns an empty string
/// for sync, non-throwing calls so the construction expression stays
/// `Type(args)` shape; otherwise returns `"try "`, `"await "`, or
/// `"try await "`. The enclosing bootstrap function is `async
/// throws` (the widest contract) so any combination is permitted
/// at the call site.
private func effectPrefix(isAsync: Bool, isThrowing: Bool) -> String {
    switch (isThrowing, isAsync) {
    case (false, false): return ""
    case (true, false): return "try "
    case (false, true): return "await "
    case (true, true): return "try await "
    }
}

/// Render a constructor's argument list. Each dependency is resolved
/// to the local-name for its `(type, key?)` identity; the argument
/// label comes from the dependency's external label (or is omitted
/// entirely for wildcard labels).
///
/// `resolvingLocal`, when supplied, lets a caller substitute an
/// expression for the local-name. The seed-scope emission uses this
/// to inline borrowed singletons at the use site (`_WireGraph.logger`
/// instead of `logger`) without first declaring a local. Returning
/// `nil` from the closure falls back to the standard local-name
/// behaviour.
private func renderArguments(
    _ dependencies: [DependencyParameter],
    resolvingLocal: ((String) -> String?)? = nil
) -> String {
    dependencies.map { dependency in
        let localName = identifierName(forType: dependency.type, key: dependency.keyIdentifier)
        let value = resolvingLocal?(localName) ?? localName
        if let label = dependency.name {
            return "\(label): \(value)"
        }
        // Wildcard external label — the call site omits it entirely.
        return value
    }.joined(separator: ", ")
}

/// Strip a type expression down to a Swift-identifier-safe form for
/// use as a property/local name. Generic instantiations are encoded
/// with `Of` and `And` separators so distinct instantiations of the
/// same base type produce distinct names:
///
///     Repository<TaskTable>          → RepositoryOfTaskTable
///     Repository<Foo, Bar<Baz>>      → RepositoryOfFooAndBarOfBaz
///     any Logger                      → anyLogger
///
/// Other special-character cases (function types, optionals, tuples,
/// etc.) drop non-identifier characters; if a future user trips over
/// a collision (two distinct bound types that sanitize to the same
/// identifier), iteration 3's diagnostic pass will detect it. Until
/// then the recommended fix is a typealias.
package func sanitizeIdentifier(_ raw: String) -> String {
    var result = ""
    for char in raw {
        switch char {
        case "<":
            result += "Of"
        case ",":
            result += "And"
        case _ where char.isLetter || char.isNumber || char == "_":
            result.append(char)
        default:
            // Everything else (whitespace, `>`, `?`, `!`, `[`, `]`,
            // `&`, `:`, `.`, `(`, `)`, `->`) is dropped silently.
            break
        }
    }
    return result
}

/// Lowercase the first character only — `B` → `b`, `TaskRepository` →
/// `taskRepository`, `DynamoDBTaskRepository` → `dynamoDBTaskRepository`.
/// The simplest convention that produces unambiguous, distinct names.
/// More sophisticated acronym-aware casing (`URLSession` →
/// `urlSession`) can be added later if generated names look awkward
/// enough to bother with.
private func lowerCamelCased(_ name: String) -> String {
    guard let first = name.first else { return name }
    return first.lowercased() + name.dropFirst()
}

// MARK: - Key check emission

/// Render the `_WireKeyChecks.swift` source the build plugin writes
/// alongside `_WireGraph.swift`. Contains one `_wireTypeCheck_*`
/// function per unique `(keyExpression, declaredType)` pair the
/// discovery found; inside each function, one `_check` call per
/// source-level usage of that pair, wrapped in `#sourceLocation`
/// directives so any compile failure is attributed back to the user's
/// source line.
///
/// The generic helper `_check<T>(_: BindingKey<T>, _: T.Type)` forces
/// Swift's type inference to unify `T` against both arguments. A
/// mismatch — `@Inject(Database.primary) var db: Cache` where
/// `Database.primary: BindingKey<Database>` — fails to compile because
/// no single `T` satisfies both. The compiler emits one error per
/// failing `_check` call, each attributed via `#sourceLocation` to the
/// originating user-source line.
///
/// Dedup: each `(keyExpression, declaredType)` pair gets one function.
/// All sites using the same pair are emitted as separate `_check`
/// calls inside that function. The success case (consistent
/// pair-usage) keeps the file size bounded; the failure case (the
/// pair mismatches) produces one Swift compile error per affected
/// site so the user can fix them all in one editing pass.
///
/// `any P` / `some P` existential property types are skipped — the
/// generic helper needs concrete `T` equality and existentials don't
/// satisfy it cleanly. Mismatches at those sites are still caught
/// later by the build plugin's missing-binding diagnostic at codegen.
///
/// The file is emitted even when there are no keyed bindings (just a
/// header comment) so SPM's declared-output-file contract holds
/// without conditional logic in the plugin.
package func renderWireKeyChecks(
    imports: [String],
    allBindings: [DiscoveredBinding]
) -> String {
    var lines: [String] = []

    lines.append("// Generated by WireGen — do not edit.")
    lines.append("//")
    lines.append("// Compile-time type assertions for keyed @Inject / @Provides")
    lines.append("// annotations. The functions below are never called; they")
    lines.append("// exist purely so the compiler unifies each key's `BindingKey<T>`")
    lines.append("// generic parameter with the consuming binding's type. A")
    lines.append("// mismatch surfaces as a Swift compile error attributed via")
    lines.append("// #sourceLocation to the user's source line.")

    let sortedImports = Array(Set(imports)).sorted()
    if !sortedImports.isEmpty {
        lines.append("")
        for line in sortedImports {
            lines.append(line)
        }
    }

    // Walk every binding, both keyed providers and keyed dependencies,
    // gathering (keyExpression, declaredType, location) for each.
    var groupedSites: [KeyCheckPair: [KeyCheckSite]] = [:]
    for site in collectKeyCheckSites(allBindings) {
        let pair = KeyCheckPair(key: site.keyExpression, type: site.declaredType)
        groupedSites[pair, default: []].append(site)
    }

    // Emit functions in deterministic (sorted) order — sort by type
    // first, then key — so the file is stable across runs.
    for (index, pair) in groupedSites.keys.sorted().enumerated() {
        let sites = (groupedSites[pair] ?? []).sorted(by: locationOrder)
        let functionName = "_wireTypeCheck_\(index + 1)"
        lines.append("")
        lines.append("private func \(functionName)() {")
        lines.append("    func _check<T>(_: BindingKey<T>, _: T.Type) {}")
        for site in sites {
            lines.append("")
            lines.append(
                "    #sourceLocation(file: \"\(site.location.file)\", line: \(site.location.line))"
            )
            lines.append("    _check(\(pair.key), \(pair.type).self)")
            lines.append("    #sourceLocation()")
        }
        lines.append("}")
    }

    lines.append("")
    return lines.joined(separator: "\n")
}

/// One source-level usage of a `(keyExpression, declaredType)` pair —
/// either a keyed `@Provides` site or a keyed `@Inject` site.
private struct KeyCheckSite {
    let keyExpression: String
    let declaredType: String
    let location: SourceLocation
}

/// Deduplication key for emitted check functions. Two sites with the
/// same `(key, type)` share a function; each contributes its own
/// `_check` call inside.
private struct KeyCheckPair: Hashable, Comparable {
    let key: String
    let type: String

    static func < (lhs: Self, rhs: Self) -> Bool {
        if lhs.type != rhs.type { return lhs.type < rhs.type }
        return lhs.key < rhs.key
    }
}

/// Stable ordering for sites within a function — file, then line, then
/// column. Ensures the emitted file is byte-for-byte deterministic
/// across runs given the same input set.
private func locationOrder(_ lhs: KeyCheckSite, _ rhs: KeyCheckSite) -> Bool {
    if lhs.location.file != rhs.location.file {
        return lhs.location.file < rhs.location.file
    }
    if lhs.location.line != rhs.location.line {
        return lhs.location.line < rhs.location.line
    }
    return lhs.location.column < rhs.location.column
}

/// Walk every binding and pull out the keyed sites we need to check.
/// Two sources: the binding side (a keyed `@Provides` claims a slot
/// `(type, key)`) and the consumer side (each keyed dependency
/// requests a slot `(type, key)`). Both must type-check against the
/// same key declaration; both contribute sites.
private func collectKeyCheckSites(_ bindings: [DiscoveredBinding]) -> [KeyCheckSite] {
    var sites: [KeyCheckSite] = []
    for binding in bindings {
        if case .provider(let provider) = binding,
            let key = provider.keyIdentifier,
            shouldEmitCheck(forType: provider.boundType)
        {
            sites.append(
                KeyCheckSite(
                    keyExpression: key,
                    declaredType: provider.boundType,
                    location: provider.location
                )
            )
        }
        for dependency in binding.dependencies {
            guard let key = dependency.keyIdentifier else { continue }
            guard shouldEmitCheck(forType: dependency.type) else { continue }
            sites.append(
                KeyCheckSite(
                    keyExpression: key,
                    declaredType: dependency.type,
                    location: dependency.location
                )
            )
        }
    }
    return sites
}

/// `any P` / `some P` existential types break the generic helper's
/// `T == T` unification — `BindingKey<P>` (concrete) and `(any P).Type`
/// don't share a `T`. We skip these and rely on the build plugin's
/// missing-binding diagnostic to catch real mismatches at codegen.
/// Documented limitation; revisit if existential-typed bindings become
/// common enough that the loss of compile-time coverage hurts.
private func shouldEmitCheck(forType type: String) -> Bool {
    !type.hasPrefix("any ") && !type.hasPrefix("some ")
}
