/// Render the `_WireGraph.swift` source the build plugin writes
/// alongside the consumer target. The generated file contains:
///
/// - The `_WireGraph` struct with one stored property per binding,
///   named by `lowerCamelCased(sanitize(boundType))`.
/// - A `Wire` façade enum whose `bootstrap()` delegates to a free
///   `_wireBootstrap()` at module scope (with `bootstrap<Container>()` /
///   `bootstrap<Scope>Scope(...)` variants for the other graphs).
/// - `_wireBootstrap()` performs the actual construction.
///
/// Why the free function: if construction ran inside a method on
/// `_WireGraph`, Swift name lookup would check the struct's members
/// before module scope. A stored property named `appName` would shadow
/// the user's module-scope `@Provides let appName` and the compiler
/// would error with "instance member cannot be used on type." The free
/// function at module scope has no enclosing type, so bare references
/// resolve straight to module scope, sidestepping the shadow entirely;
/// the `Wire` façade just forwards to it.
///
/// Inside the free function, bare local names are safe even when they
/// equal a module-scope identifier — Swift's `let x = x` resolves the
/// RHS in the surrounding scope before the LHS is bound, so the local
/// shadows the outer correctly without self-reference issues.
///
/// `imports` are propagated verbatim from the input source files so
/// every type referenced by a binding stays in scope. The naive
/// "union all imports" approach can include unrelated imports that
/// happen to live in the same file as a binding — harmless for an
/// internal generated file. Iteration 7's cross-module work will
/// refine this if generated-file noise becomes a real complaint.
///
/// `bootstrap` is declared `async throws` regardless of whether the
/// current set of bindings actually have async/throws inits. M6's
/// lifecycle work makes async/throws constructor injection a
/// first-class option, and locking the signature in now means later
/// migrations don't ripple through every consumer's `try await
/// Wire.bootstrap()` call site. Swift accepts an `async throws`
/// function body that doesn't actually use those capabilities.
package func renderWireGraph(
    imports: [String],
    topologicalOrder: [DiscoveredBinding],
    containerTopologicalOrders: [String: [DiscoveredBinding]] = [:],
    seedScopeOrders: [SeedScopeEmission] = [],
    graphConformances: [DiscoveredGraphConformance] = [],
    multibindingKeys: [DiscoveredMultibindingKey] = []
) -> String {
    var lines: [String] = []
    var bootstrapEntries: [BootstrapEntry] = []

    lines.append("// Generated by WireGen — do not edit.")

    // Imports — sorted and deduplicated for stability across runs.
    let sortedImports = Array(Set(imports)).sorted()
    if !sortedImports.isEmpty {
        lines.append("")
        for line in sortedImports {
            lines.append(line)
        }
    }

    // Default graph — always emitted, even when empty, so consumers
    // can call `Wire.bootstrap()` unconditionally.
    appendStruct(
        structName: "_WireGraph",
        bootstrapFunction: "_wireBootstrap",
        bootstrapMethod: "bootstrap",
        topologicalOrder: topologicalOrder,
        into: &lines,
        entries: &bootstrapEntries
    )

    // Per-container graphs — sorted by container name for deterministic
    // output. Each gets its own struct + free-function pair following
    // the same delegation pattern as the default. The free-function
    // discriminator is the container name so multiple containers don't
    // collide at module scope.
    for (containerName, order) in containerTopologicalOrders.sorted(by: { $0.key < $1.key }) {
        appendStruct(
            structName: "_\(containerName)WireGraph",
            bootstrapFunction: "_wireBootstrap\(containerName)",
            bootstrapMethod: "bootstrap\(containerName)",
            topologicalOrder: order,
            into: &lines,
            entries: &bootstrapEntries
        )
    }

    // Per-seed scope graphs. Each emits a `_<Suffix>WireScope` struct
    // whose `bootstrap(seed:wireGraph:)` takes the externally-owned
    // seed value and the wire graph; the body aliases singleton
    // dependencies as locals via the synthetic-borrow bindings, then
    // constructs scope-bound bindings in topological order.
    for scope in seedScopeOrders.sorted(by: { $0.identifierSuffix < $1.identifierSuffix }) {
        appendSeedScopeStruct(scope: scope, into: &lines, entries: &bootstrapEntries)
    }

    // Setter extensions for `@Inject weak var` on actor consumers.
    // Aggregated across every graph + scope so each actor type's
    // setters emit once at module scope, regardless of how many
    // partitions reference it.
    let allBindings =
        topologicalOrder
        + containerTopologicalOrders.values.flatMap { $0 }
        + seedScopeOrders.flatMap { $0.topologicalOrder }
    lines.append(contentsOf: renderActorWeakSetterExtensions(for: allBindings))

    // Adapter-declared graph conformances — `extension _WireGraph: <Protocol>`
    // mapping the protocol's members to the default graph's aggregate bindings.
    appendGraphConformances(
        graphConformances,
        topologicalOrder: topologicalOrder,
        multibindingKeys: multibindingKeys,
        into: &lines
    )

    // The `Wire` façade — one uniform, non-generic entry point per graph.
    // Emitted last so it's a single stable trailing block.
    appendWireFacade(bootstrapEntries, into: &lines)

    // Trailing newline at end of file. `appendStruct` is leading-blank
    // only, so the final struct's closing `}` doesn't end the file
    // without it.
    lines.append("")

    return lines.joined(separator: "\n")
}

/// Emission-side description of one per-seed scope graph. Mirrors
/// the orchestration result's relevant fields: the seed type
/// expression for the bootstrap seed-parameter type, the parent
/// graph type for the bootstrap wire-graph-parameter type
/// (`_WireGraph` for default-graph seeded scopes,
/// `_<Container>WireGraph` for container-scope ones), the identifier
/// suffix for the struct/function names, the topological order over
/// the combined graph, and the borrowed-binding property names so
/// the emitter knows which entries are singletons aliased from the
/// `wireGraph:` bootstrap parameter rather than constructed in place.
package struct SeedScopeEmission: Sendable {
    package let seedTypeExpression: String
    package let identifierSuffix: String
    package let parentGraphType: String
    package let topologicalOrder: [DiscoveredBinding]
    package let borrowedBindingPropertyNames: Set<String>

    package init(
        seedTypeExpression: String,
        identifierSuffix: String,
        parentGraphType: String,
        topologicalOrder: [DiscoveredBinding],
        borrowedBindingPropertyNames: Set<String>
    ) {
        self.seedTypeExpression = seedTypeExpression
        self.identifierSuffix = identifierSuffix
        self.parentGraphType = parentGraphType
        self.topologicalOrder = topologicalOrder
        self.borrowedBindingPropertyNames = borrowedBindingPropertyNames
    }
}

/// Emit one `_<Suffix>WireScope` struct + matching
/// `_wireBootstrap<Suffix>Scope` free function pair. The bootstrap
/// takes `(seed:, wireGraph:)` parameters. Borrowed singleton
/// bindings in the topological order are not declared as locals —
/// each borrow's `accessPath` (`<wireGraphLocal>.<prop>`) is inlined
/// at every consumer's arg site via the `resolvingLocal` hook on
/// `renderArguments`. The synthetic seed binding shadow-binds from
/// the parameter (`let X = X`) and is skipped via the
/// `local != construction` check. Net result: only scope-bound
/// bindings emit `let` lines, borrowed singletons appear at use
/// sites only, and unused borrows produce no output.
private func appendSeedScopeStruct(
    scope: SeedScopeEmission,
    into lines: inout [String],
    entries: inout [BootstrapEntry]
) {
    let structName = "_\(scope.identifierSuffix)WireScope"
    let bootstrapFunction = "_wireBootstrap\(scope.identifierSuffix)Scope"
    let storedBindings = scope.topologicalOrder.filter {
        !scope.borrowedBindingPropertyNames.contains(propertyName(for: $0))
    }
    // Both bootstrap parameters use type-anchored labels rather than
    // role-anchored ones. The seed parameter keeps `seed:` as its
    // external label (the role here is fixed) but uses the seed
    // type's property-name form as its internal name. The wire-graph
    // parameter's external label is the parent-graph type's stripped
    // lowerCamel form (`wireGraph:` for `_WireGraph`,
    // `testContainerWireGraph:` for `_TestContainerWireGraph`) so
    // varying parent-graph types don't share the same label. Its
    // internal name is that external label prefixed with `_` so a
    // user binding whose property name resolves to `wireGraph` or
    // `testContainerWireGraph` can coexist without colliding on the
    // local-variable token inside the bootstrap body.
    let seedLocal = identifierName(forType: scope.seedTypeExpression, key: nil)
    let wireGraphExternal = wireGraphParameterLabel(forType: scope.parentGraphType)
    let wireGraphInternal = wireGraphParameterInternalName(forType: scope.parentGraphType)

    // The seed scope's bootstrap entry point on the `Wire` façade — keeps the
    // `(seed:, <parentGraph>:)` parameter shape, forwarding to the private
    // free function.
    entries.append(
        BootstrapEntry(
            signature:
                "bootstrap\(scope.identifierSuffix)Scope(seed: \(scope.seedTypeExpression), \(wireGraphExternal): \(scope.parentGraphType)) async throws -> \(structName)",
            body: "try await \(bootstrapFunction)(seed: seed, \(wireGraphExternal): \(wireGraphExternal))"
        )
    )

    // Borrowed-singleton bindings get inlined at their consumers' arg
    // sites rather than declared as locals — every consumer in the
    // topo order resolves a borrow dep directly to the wire-graph
    // expression (`_WireGraph.logger`). The map's keys are borrow
    // property names; values are the substitution expressions read
    // straight off each borrow's `accessPath`. Unused borrows produce
    // no output: their let-lines are skipped and no consumer refers
    // to them, so they vanish from the emitted bootstrap.
    var borrowAccessPaths: [String: String] = [:]
    for binding in scope.topologicalOrder {
        let name = propertyName(for: binding)
        guard scope.borrowedBindingPropertyNames.contains(name),
            case .provider(let provider) = binding
        else { continue }
        borrowAccessPaths[name] = provider.accessPath
    }
    let resolveBorrow: (String) -> String? = { borrowAccessPaths[$0] }

    lines.append("")
    // No explicit `Sendable` conformance — Swift auto-derives it when
    // every stored binding is itself `Sendable` (the dominant case:
    // every server-side `@Singleton` / `@Provides` binding is
    // typically Sendable). When a binding *isn't* Sendable (e.g. a
    // class with `weak var` that's neither `@MainActor` nor
    // `@unchecked Sendable`), the struct is non-Sendable too, and
    // the compiler surfaces that at the *use site* (where the user
    // tries to cross an isolation boundary) rather than at the
    // generated struct declaration. Right place for the trade-off:
    // the user chose the binding's isolation story, Wire respects it.
    lines.append("internal struct \(structName) {")
    for binding in storedBindings {
        let property = propertyName(for: binding)
        lines.append("    let \(property): \(binding.boundTypeReference)")
    }
    lines.append("}")

    lines.append("")
    lines.append(
        "private func \(bootstrapFunction)(seed \(seedLocal): \(scope.seedTypeExpression), \(wireGraphExternal) \(wireGraphInternal): \(scope.parentGraphType)) async throws -> \(structName) {"
    )

    if scope.topologicalOrder.isEmpty && storedBindings.isEmpty {
        lines.append("    \(structName)()")
        lines.append("}")
        return
    }

    for binding in scope.topologicalOrder {
        let local = propertyName(for: binding)
        // Borrows are inlined at their consumers' arg sites — no let-
        // line is needed (or wanted: unused borrows would otherwise
        // leave dead lines in the emitted bootstrap).
        if scope.borrowedBindingPropertyNames.contains(local) { continue }
        let construction = constructionExpression(for: binding, resolvingLocal: resolveBorrow)
        // Skip a redundant `let X = X` shadow: it happens when the
        // construction expression equals the local name, which inside
        // the seed bootstrap means the synthetic seed binding whose
        // access path is the parameter's internal name. Subsequent
        // bare references resolve to the parameter directly. The same
        // shadow on a module-scope provider would cross from module
        // scope into the function — that path stays in `appendStruct`
        // and isn't affected.
        guard local != construction else { continue }
        lines.append("    let \(local) = \(construction)")
    }

    // Post-init member injection block for bindings constructed in
    // this scope. Borrowed bindings are skipped — their post-init
    // wiring (if any) belongs to the scope that owns them. Member
    // injection parameters pointing at a borrowed target route
    // through `resolveBorrow` so the assignment / method call uses
    // the borrow's access path (`_WireGraph.logger`) rather than a
    // non-existent local.
    lines.append(
        contentsOf: renderMemberInjections(
            for: scope.topologicalOrder,
            resolvingLocal: resolveBorrow,
            skipConsumers: scope.borrowedBindingPropertyNames
        )
    )

    let returnArgs = storedBindings.map { binding -> String in
        let name = propertyName(for: binding)
        return "\(name): \(name)"
    }.joined(separator: ", ")
    lines.append("    return \(structName)(\(returnArgs))")
    lines.append("}")
}

/// The stored-property type for a binding on the generated `_WireGraph` struct:
/// - a bare `some P` lift node uses its own lifted parameter (`T0`);
/// - a structural lift node reuses its dependencies' parameters, spelled
///   `Controller<T1>` — each `some <constraint>` sub-term replaced by the lifted
///   parameter of the matching bridge target;
/// - everything else uses its concrete `boundTypeReference` (qualified for a
///   nested `@Singleton`).
private func wireGraphFieldType(
    for binding: DiscoveredBinding,
    liftedParameterForIdentity: [String: String]
) -> String {
    if let parameter = liftedParameterForIdentity[canonicalTypeName(binding.boundType)] {
        return parameter
    }
    guard binding.allGenericParametersDetermined else {
        return binding.boundTypeReference
    }
    let arguments = binding.genericParameterNames.map { parameter -> String in
        let constraint = binding.genericParameterConstraints[parameter] ?? ""
        return liftedParameterForIdentity[canonicalTypeName("some \(constraint)")]
            ?? "some \(constraint)"
    }
    return "\(binding.boundTypeReference)<\(arguments.joined(separator: ", "))>"
}

/// Emit one `_<Name>WireGraph` struct + matching `_wireBootstrap<Name>`
/// free function pair. Called once for the default graph and once per
/// container; the same shape carries through for both.
private func appendStruct(
    structName: String,
    bootstrapFunction: String,
    bootstrapMethod: String,
    topologicalOrder: [DiscoveredBinding],
    into lines: inout [String],
    entries: inout [BootstrapEntry]
) {
    // Bindings whose graph identity is opaque (`some P`) each lift a generic
    // parameter onto the struct, so a stored `some P` property refers to one
    // concrete type rather than a fresh opaque type per access. The parameter's
    // constraint is the binding's declared protocol; the bootstrap builds the
    // concrete value and the structural opaque return type binds it.
    let opaqueBindings = topologicalOrder.filter { $0.boundType.hasPrefix("some ") }
    let liftedConstraints = opaqueBindings.map { String($0.boundType.dropFirst("some ".count)) }
    // Map each bare `some P` identity to its lifted parameter (`some TaskRepo`
    // → `T1`) so a structural lift node can reuse it, spelled `Controller<T1>`.
    var liftedParameterForIdentity: [String: String] = [:]
    for (index, binding) in opaqueBindings.enumerated() {
        liftedParameterForIdentity[canonicalTypeName(binding.boundType)] = "T\(index)"
    }
    let genericClause =
        liftedConstraints.isEmpty
        ? ""
        : "<"
            + liftedConstraints.enumerated()
            .map { "T\($0.offset): \($0.element)" }
            .joined(separator: ", ") + ">"
    // The `_wireBootstrap` free function and the `Wire` façade both return the
    // opaque-erased form `\(structName)<some P0, …>`; Swift infers each parameter
    // from the concrete values the bootstrap returns.
    let openReturnType =
        liftedConstraints.isEmpty
        ? structName
        : "\(structName)<" + liftedConstraints.map { "some \($0)" }.joined(separator: ", ") + ">"

    // The bootstrap entry point lives on the `Wire` façade, not on the struct
    // — a non-generic call site that stays `Wire.\(bootstrapMethod)()` whether
    // or not the struct carries lifted parameters.
    entries.append(
        BootstrapEntry(
            signature: "\(bootstrapMethod)() async throws -> \(openReturnType)",
            body: "try await \(bootstrapFunction)()"
        )
    )

    lines.append("")
    // No explicit `Sendable` — see the matching comment in
    // `appendSeedScopeStruct` for the rationale. Auto-derivation
    // handles the conformance when all bindings are Sendable; the
    // user gets compile-time feedback at their use site if one
    // isn't.
    // Conforms to `Introspectable` (the `introspect()` below satisfies it) so a facade
    // can accept `some Introspectable` without naming the concrete graph type.
    lines.append("internal struct \(structName)\(genericClause): Introspectable {")

    // Stored properties — one per binding, type-derived name, no
    // prefix. Users access these as `graph.logger`, `graph.userService`.
    // A bare `some P` lift node uses its lifted parameter (`T0`); a structural
    // lift node reuses its dependencies' parameters (`Controller<T1>`); the rest
    // use `boundTypeReference` so nested `@Singleton`s inside a `@Container`
    // qualify with the enclosing path (`TestContainer.MockService`) — required
    // because this struct lives at module scope.
    for binding in topologicalOrder {
        let property = propertyName(for: binding)
        let type = wireGraphFieldType(
            for: binding,
            liftedParameterForIdentity: liftedParameterForIdentity
        )
        lines.append("    let \(property): \(type)")
    }
    lines.append(contentsOf: introspectionMethodLines(topologicalOrder))
    lines.append("}")

    // Free function at module scope — does the actual construction.
    // Module-scope context means bare `appName` / `logger` references
    // resolve cleanly to module-scope `@Provides` declarations,
    // bypassing the type-member shadow that would happen inside
    // the struct's `static func bootstrap()` directly.
    lines.append("")
    lines.append("private func \(bootstrapFunction)() async throws -> \(openReturnType) {")

    guard !topologicalOrder.isEmpty else {
        // Empty graph — no bindings, return the empty memberwise init.
        lines.append("    \(structName)()")
        lines.append("}")
        return
    }

    // Construction body — bare local names. `let logger = logger`
    // works because Swift resolves the RHS in the outer scope before
    // binding the LHS local, so the local shadows cleanly.
    for binding in topologicalOrder {
        // A builder aggregate emits a `@resultBuilder`-annotated local
        // function (capturing the contributor locals) plus its call —
        // the attribute can't sit on a closure, so it can't be a single
        // expression like the other forms.
        if case .aggregate(let aggregate) = binding, aggregate.flavour == .builder {
            lines.append(contentsOf: builderFoldLines(aggregate))
            continue
        }
        let local = propertyName(for: binding)
        let construction = constructionExpression(for: binding)
        // A specialised generic `@Provides func` can't be called with explicit
        // type arguments, so annotate the local with the concrete return type
        // and let Swift infer them (`let repo: Repository<DynamoDBTable> =
        // makeRepo()`). Harmless when the value arguments already determine them.
        if case .provider(let provider) = binding, !provider.concreteGenericArguments.isEmpty {
            lines.append("    let \(local): \(binding.boundTypeReference) = \(construction)")
        } else {
            lines.append("    let \(local) = \(construction)")
        }
    }

    // Post-init member injection block — emits after all locals
    // are bound so each injection's target references are in
    // scope. Empty when no `@Inject weak var` sugar or
    // `@Inject func` member injections exist in the graph.
    lines.append(contentsOf: renderMemberInjections(for: topologicalOrder))

    // Final return — memberwise init takes one argument per stored
    // property in declaration order. Label is the property name;
    // value is the matching local.
    let returnArgs = topologicalOrder.map { binding -> String in
        let name = propertyName(for: binding)
        return "\(name): \(name)"
    }.joined(separator: ", ")
    lines.append("    return \(structName)(\(returnArgs))")

    lines.append("}")
}

/// The `func introspect() -> WiringModel` emitted on the graph struct: a read-only
/// view of the graph, baked in at codegen (Wire is compile-time DI, so no runtime
/// reflection). One `BindingInfo` per binding in construction order.
private func introspectionMethodLines(_ topologicalOrder: [DiscoveredBinding]) -> [String] {
    var lines: [String] = []
    lines.append("")
    lines.append("    func introspect() -> WiringModel {")
    if topologicalOrder.isEmpty {
        lines.append("        WiringModel(bindings: [])")
    } else {
        lines.append("        WiringModel(bindings: [")
        for binding in topologicalOrder {
            lines.append("            \(bindingInfoLiteral(binding)),")
        }
        lines.append("        ])")
    }
    lines.append("    }")
    return lines
}

/// A `BindingInfo(...)` literal for one binding — bound type, key, kind, scope, and
/// dependency edges (for an aggregate, `binding.dependencies` surfaces the contributors).
private func bindingInfoLiteral(_ binding: DiscoveredBinding) -> String {
    let (kind, scope) = introspectionKindAndScope(binding)
    let dependencies = binding.dependencies
        .map {
            "DependencyEdge(type: \(swiftStringLiteral($0.type)), "
                + "key: \(optionalSwiftStringLiteral($0.keyIdentifier)))"
        }
        .joined(separator: ", ")
    let location = binding.location
    let locationLiteral =
        "SourceLocation(module: \(swiftStringLiteral(binding.originModule)), "
        + "file: \(swiftStringLiteral(location.file)), line: \(location.line))"
    return "BindingInfo("
        + "type: \(swiftStringLiteral(binding.boundType)), "
        + "key: \(optionalSwiftStringLiteral(binding.keyIdentifier)), "
        + "kind: .\(kind), "
        + "scope: \(optionalSwiftStringLiteral(scope)), "
        + "dependencies: [\(dependencies)], "
        + "location: \(locationLiteral))"
}

/// The `BindingKind` case name and scope seed for a binding: a scoped type binding
/// carries its seed; a plain `@Singleton` is app-scoped (nil seed).
private func introspectionKindAndScope(_ binding: DiscoveredBinding) -> (kind: String, scope: String?) {
    switch binding {
    case .scopeBound(let type):
        if let seed = type.scopeKey?.seed { return ("scoped", seed) }
        return ("singleton", nil)
    case .provider(let provider):
        return ("provider", provider.scopeKey?.seed)
    case .aggregate:
        return ("aggregate", nil)
    }
}

/// A Swift string literal for a type name. Type names from SwiftSyntax hold only type
/// syntax (`<`, `>`, `[`, `&`, `.`, spaces) — never a quote or backslash — so no
/// escaping is needed.
private func swiftStringLiteral(_ value: String) -> String {
    "\"\(value)\""
}

private func optionalSwiftStringLiteral(_ value: String?) -> String {
    value.map(swiftStringLiteral) ?? "nil"
}

/// The stored-property name on `_WireGraph` and the local name in
/// `_wireBootstrap()` for a given binding. Type-derived: bindings are
/// identified by what they produce, not by their source-level
/// declaration name. Keyed bindings append a key-derived suffix so
/// that two providers of the same type with different keys don't
/// collide. See `identifierName(forType:key:)` for the rule.
func propertyName(for binding: DiscoveredBinding) -> String {
    identifierName(forType: binding.boundType, key: binding.keyIdentifier)
}

/// The canonical local/property name for a `(boundType, key?)` pair.
/// Used for both binding declarations and dependency-resolution sites
/// so a keyed dependency points at the matching keyed binding's local.
/// Also called from `Graph.swift` to detect generated-accessor-name
/// collisions before codegen runs.
///
/// Rules:
/// - Unkeyed: `lowerCamel(sanitize(type))` — same as before keys
///   existed.
/// - Keyed: `lowerCamel(sanitize(type)) + "Keyed" + upperCamel(sanitize(key))`.
///
/// The `Keyed` infix is a sentinel segment matching the `Of`/`And`
/// separator pattern already used for generic instantiations
/// (`Repository<TaskTable>` → `RepositoryOfTaskTable`). It pushes the
/// collision space to "type names that literally contain the word
/// `Keyed` in the matching position," which doesn't happen in real
/// code. The verbose readout — `databaseKeyedDatabasePrimary` for
/// `(Database, "Database.primary")` — is a tradeoff: less ergonomic
/// than a stripped form (`databasePrimary`) but unambiguous, and the
/// keyed accessor is rarely the user's primary access path anyway
/// (keyed bindings usually live behind a consumer).
func identifierName(forType type: String, key: String?) -> String {
    let typeName = lowerCamelCased(sanitizeIdentifier(type))
    guard let key else { return typeName }
    let keySuffix = upperCamelCased(sanitizeKeyComponents(key))
    return typeName + "Keyed" + keySuffix
}

/// Sanitize a key expression for use inside an identifier. Dots are
/// treated as segment separators — the next letter is upper-cased,
/// the dot is dropped. Other non-identifier characters are dropped
/// silently, matching `sanitizeIdentifier`'s posture.
///
///     "primary"            → "primary"
///     "Database.primary"   → "DatabasePrimary"
///     "Module.Database.x"  → "ModuleDatabaseX"
private func sanitizeKeyComponents(_ raw: String) -> String {
    var result = ""
    var capitalizeNext = false
    for char in raw {
        if char == "." {
            capitalizeNext = true
            continue
        }
        guard char.isLetter || char.isNumber || char == "_" else { continue }
        if capitalizeNext {
            result += String(char).uppercased()
            capitalizeNext = false
        } else {
            result.append(char)
        }
    }
    return result
}

/// Uppercase the first character only — the symmetric counterpart to
/// `lowerCamelCased`. Used to make a key suffix capitalised so it
/// reads as a distinct word in the composed identifier
/// (`appName` + `Alternate` → `appNameAlternate`).
private func upperCamelCased(_ name: String) -> String {
    guard let first = name.first else { return name }
    return first.uppercased() + name.dropFirst()
}

/// Conventional name of the setter extension method WireGen
/// synthesises for `@Inject weak var <property>` on an actor host.
/// Class hosts use direct property assignment and don't need this.
/// `_wire` prefix reserves the name space against collisions with
/// user-written members.
private func actorWeakSetterName(forProperty propertyName: String) -> String {
    "_wireSet\(upperCamelCased(propertyName))"
}

/// Emit `extension <Actor> { func _wireSet<Property>(_ value: T) {
/// self.<property> = value } }` blocks for every weak `@Inject`
/// property on an actor host type that appears in the topological
/// order. Direct property assignment from outside an actor's
/// isolation isn't legal Swift, so the setter extension is the
/// language-supported mechanism — the method is implicitly actor-
/// isolated, and codegen's post-init call site invokes it with
/// `await`.
///
/// Deduplicates by `(consumer type, property name)` so a type
/// bound in multiple graph partitions still emits the extension
/// once at the module level. Extensions emit AFTER all struct/
/// bootstrap blocks so the file's main shape (structs first,
/// per-type extensions afterwards) reads top-down.
private func renderActorWeakSetterExtensions(
    for bindings: [DiscoveredBinding]
) -> [String] {
    var seen: Set<String> = []
    var perType: [(typeReference: String, setters: [(name: String, propertyName: String, type: String)])] = []
    var typeIndex: [String: Int] = [:]
    for binding in bindings where binding.consumerIsActor {
        guard case .scopeBound(let scopeBound) = binding else { continue }
        for injection in scopeBound.memberInjections {
            guard case .propertyAssignment(let propertyName) = injection.shape else { continue }
            guard let parameter = injection.parameters.first else { continue }
            let dedupeKey = "\(scopeBound.qualifiedTypeName)::\(propertyName)"
            guard !seen.contains(dedupeKey) else { continue }
            seen.insert(dedupeKey)
            let setter = (
                name: actorWeakSetterName(forProperty: propertyName),
                propertyName: propertyName,
                type: parameter.type
            )
            if let index = typeIndex[scopeBound.qualifiedTypeName] {
                perType[index].setters.append(setter)
            } else {
                typeIndex[scopeBound.qualifiedTypeName] = perType.count
                perType.append((scopeBound.qualifiedTypeName, [setter]))
            }
        }
    }
    var lines: [String] = []
    for entry in perType {
        lines.append("")
        lines.append("extension \(entry.typeReference) {")
        for setter in entry.setters {
            lines.append("    func \(setter.name)(_ value: \(setter.type)) {")
            lines.append("        self.\(setter.propertyName) = value")
            lines.append("    }")
        }
        lines.append("}")
    }
    return lines
}

/// The RHS expression that constructs a single binding inside
/// `bootstrap()`. Uses bare references — the consumer's source-file
/// imports are propagated to the generated file so user-supplied
/// symbols are in scope without qualification.
///
/// `resolvingLocal` is forwarded to `renderArguments` so per-graph
/// dependency substitutions (e.g., the seed-scope path inlining
/// borrowed singletons at use sites) flow through.
private func constructionExpression(
    for binding: DiscoveredBinding,
    resolvingLocal: ((String) -> String?)? = nil
) -> String {
    switch binding {
    case .scopeBound(let scopeBound):
        // Generic instantiations (`Repository<TaskTable>`) keep their
        // angle brackets at the call site since Swift's syntax accepts
        // that. `qualifiedTypeName` includes any enclosing-type
        // prefix (e.g. `TestContainer.MockService`) so a `@Singleton`
        // nested inside a `@Container` resolves correctly when called
        // from the module-scope `_wireBootstrap...` free function.
        let args = renderArguments(scopeBound.dependencies, consumer: binding, resolvingLocal: resolvingLocal)
        let call = "\(scopeBound.qualifiedTypeName)(\(args))"
        return effectPrefix(
            isAsync: scopeBound.initIsAsync,
            isThrowing: scopeBound.initIsThrowing
        ) + call
    case .provider(let provider):
        let prefix = effectPrefix(
            isAsync: provider.isAsync,
            isThrowing: provider.isThrowing
        )
        switch provider.form {
        case .property:
            return prefix + provider.accessPath
        case .function:
            let args = renderArguments(provider.dependencies, consumer: binding, resolvingLocal: resolvingLocal)
            // Always a bare call: Swift forbids explicit specialisation of a
            // function (`makeRepo<DynamoDBTable>()` is illegal — unlike a type
            // initialiser). A specialised generic provider function infers its
            // type arguments instead — from its value arguments, or from the
            // concrete-return-typed local `appendStruct` annotates.
            return "\(prefix)\(provider.accessPath)(\(args))"
        }
    case .aggregate(let aggregate):
        return aggregateConstruction(aggregate, resolvingLocal: resolvingLocal)
    }
}

/// Emit an aggregate's construction: a collection literal over the
/// contributor locals, coerced to the declared collection type so the
/// heterogeneous concrete elements unify (`[a, b] as [any P]`). Each
/// contributor is referenced by the same local name its own binding
/// emits. The builder fold lands in Step 5b.
private func aggregateConstruction(
    _ aggregate: DiscoveredAggregate,
    resolvingLocal: ((String) -> String?)?
) -> String {
    func local(for contributor: AggregateContributor) -> String {
        let name = identifierName(
            forType: contributor.dependency.type,
            key: contributor.dependency.keyIdentifier
        )
        return resolvingLocal?(name) ?? name
    }
    switch aggregate.flavour {
    case .collected:
        let elements = aggregate.contributors.map(local).joined(separator: ", ")
        return "[\(elements)] as \(aggregate.collectionType)"
    case .mapped:
        if aggregate.contributors.isEmpty {
            return "[:] as \(aggregate.collectionType)"
        }
        let pairs = aggregate.contributors.map { contributor in
            "\(contributor.mapKeyExpression ?? "_"): \(local(for: contributor))"
        }.joined(separator: ", ")
        return "[\(pairs)] as \(aggregate.collectionType)"
    case .builder:
        // Builder aggregates are emitted by `builderFoldLines` in the
        // bootstrap body (a local function + call), not as a single
        // expression, so this is never reached.
        preconditionFailure("builder aggregate is emitted via builderFoldLines")
    }
}

/// Emit a builder aggregate as a `@resultBuilder`-annotated local
/// function listing the contributor locals in order, followed by its
/// invocation binding the aggregate local. The function captures the
/// already-constructed contributor locals (topological order guarantees
/// they precede the aggregate), so it takes no parameters.
private func builderFoldLines(_ aggregate: DiscoveredAggregate) -> [String] {
    let aggregateLocal = identifierName(forType: aggregate.collectionType, key: aggregate.keyReference)
    let foldName = "_wireFold" + upperCamelCased(sanitizeKeyComponents(aggregate.keyReference))
    let builderType = aggregate.builderTypeName ?? ""
    var lines = [
        "    @\(builderType)",
        "    func \(foldName)() -> \(aggregate.collectionType) {",
    ]
    for contributor in aggregate.contributors {
        let local = identifierName(
            forType: contributor.dependency.type,
            key: contributor.dependency.keyIdentifier
        )
        lines.append("        \(local)")
    }
    lines.append("    }")
    lines.append("    let \(aggregateLocal) = \(foldName)()")
    return lines
}

/// Combine `isAsync` / `isThrowing` into the call-site prefix Swift
/// expects on an effectful call expression. Returns an empty string
/// for sync, non-throwing calls so the construction expression stays
/// `Type(args)` shape; otherwise returns `"try "`, `"await "`, or
/// `"try await "`. The enclosing bootstrap function is `async
/// throws` (the widest contract) so any combination is permitted
/// at the call site.
private func effectPrefix(isAsync: Bool, isThrowing: Bool) -> String {
    switch (isThrowing, isAsync) {
    case (false, false): return ""
    case (true, false): return "try "
    case (false, true): return "await "
    case (true, true): return "try await "
    }
}

/// Render a constructor's argument list. Each dependency is resolved
/// to the local-name for its `(type, key?)` identity; the argument
/// label comes from the dependency's external label (or is omitted
/// entirely for wildcard labels).
///
/// `resolvingLocal`, when supplied, lets a caller substitute an
/// expression for the local-name. The seed-scope emission uses this
/// to inline borrowed singletons at the use site (`_WireGraph.logger`
/// instead of `logger`) without first declaring a local. Returning
/// `nil` from the closure falls back to the standard local-name
/// behaviour.
private func renderArguments(
    _ dependencies: [DependencyParameter],
    consumer: DiscoveredBinding? = nil,
    resolvingLocal: ((String) -> String?)? = nil
) -> String {
    dependencies
        .map { dependency in
            // Resolve against the bridged identity so a constrained-parameter
            // dependency (`table: Table`) references its `some P` producer's
            // local (`someDBTable`), not a `table` local that doesn't exist.
            // For every other dependency this is its own identity, unchanged.
            let identity = consumer.map { bridgedDependencyIdentity(dependency, in: $0) } ?? dependency.identity
            let localName = identifierName(forType: identity.displayType, key: identity.key)
            let value = resolvingLocal?(localName) ?? localName
            if let label = dependency.name {
                return "\(label): \(value)"
            }
            // Wildcard external label — the call site omits it entirely.
            return value
        }.joined(separator: ", ")
}

/// Emit the post-construction member-injection block for every
/// binding in the topological order. Each `MemberInjection`
/// renders to one source line — either a property assignment
/// (`consumer.prop = parameter`) or a method call
/// (`[try] [await] consumer.method(args...)`), chosen by the
/// injection's `Shape`.
///
/// The block emits *after* all construction lines so every target
/// reference is in scope as a local. Cycle-breaking comes from
/// this two-phase structure: the graph's init-time-edge topo sort
/// decides construction order, and the member-injection block
/// closes any post-construction wiring (including cycles whose
/// other side is a weak ref or a setter method).
///
/// `resolvingLocal`, when supplied, lets the seed-scope path
/// inline borrowed singletons at the target reference — same
/// callback shape as `renderArguments`. A member injection
/// parameter pointing at a borrowed binding resolves through the
/// borrow's `_WireGraph.foo` access path rather than a local.
///
/// `skipConsumers` excludes bindings that aren't constructed in
/// the current scope (e.g. borrowed singletons inside a seed
/// scope's bootstrap). Their post-init wiring belongs to whichever
/// scope owns their construction, not to scopes that merely
/// reference them.
private func renderMemberInjections(
    for topologicalOrder: [DiscoveredBinding],
    resolvingLocal: ((String) -> String?)? = nil,
    skipConsumers: Set<String> = []
) -> [String] {
    var lines: [String] = []
    for binding in topologicalOrder {
        let consumerLocal = propertyName(for: binding)
        if skipConsumers.contains(consumerLocal) { continue }
        for injection in binding.memberInjections {
            let args = renderArguments(injection.parameters, consumer: binding, resolvingLocal: resolvingLocal)
            switch injection.shape {
            case .propertyAssignment(let propertyName):
                // Sugar form for `@Inject weak var`. For class
                // consumers, direct property assignment is the
                // natural Swift idiom — zero-overhead and lines up
                // with what the user would have written manually.
                // For actor consumers, direct assignment from
                // outside isolation isn't legal Swift; codegen
                // routes the write through a synthesised setter
                // extension method (`_wireSet<Property>`) emitted
                // elsewhere in the generated file, and the call
                // crosses isolation via `await`.
                if binding.consumerIsActor {
                    let setterName = actorWeakSetterName(forProperty: propertyName)
                    lines.append("    await \(consumerLocal).\(setterName)(\(args))")
                } else {
                    lines.append("    \(consumerLocal).\(propertyName) = \(args)")
                }
            case .methodCall(let methodName):
                // General form: user-written method, may have any
                // effect colour. The prefix combines the method's
                // own effects with the consumer's isolation: calling
                // any method on an actor from outside its isolation
                // requires `await` regardless of whether the method
                // itself is declared `async` (the await pays for the
                // isolation crossing, not for the method's
                // asynchrony). `consumerIsActor` folds into `isAsync`
                // at the call site so `effectPrefix` stays
                // single-purpose.
                let prefix = effectPrefix(
                    isAsync: injection.isAsync || binding.consumerIsActor,
                    isThrowing: injection.isThrowing
                )
                lines.append("    \(prefix)\(consumerLocal).\(methodName)(\(args))")
            }
        }
    }
    return lines
}

/// Strip a type expression down to a Swift-identifier-safe form for
/// use as a property/local name. Generic instantiations are encoded
/// with `Of` and `And` separators so distinct instantiations of the
/// same base type produce distinct names:
///
///     Repository<TaskTable>          → RepositoryOfTaskTable
///     Repository<Foo, Bar<Baz>>      → RepositoryOfFooAndBarOfBaz
///     any Logger                      → anyLogger
///
/// Other special-character cases (function types, optionals, tuples,
/// etc.) drop non-identifier characters; if a future user trips over
/// a collision (two distinct bound types that sanitize to the same
/// identifier), iteration 3's diagnostic pass will detect it. Until
/// then the recommended fix is a typealias.
package func sanitizeIdentifier(_ raw: String) -> String {
    var result = ""
    // Upper-camel the first letter after an `Of`/`And` boundary so the segment
    // reads as camelCase — `Controller<some TaskRepo>` →
    // `ControllerOfSomeTaskRepo`, not `...OfsomeTaskRepo`. Concrete type
    // arguments already start uppercase, so only `some`/`any` change.
    var capitalizeNext = false
    for char in raw {
        switch char {
        case "<":
            result += "Of"
            capitalizeNext = true
        case ",":
            result += "And"
            capitalizeNext = true
        case _ where char.isLetter || char.isNumber || char == "_":
            result += capitalizeNext ? char.uppercased() : String(char)
            capitalizeNext = false
        default:
            // Everything else (whitespace, `>`, `?`, `!`, `[`, `]`,
            // `&`, `:`, `.`, `(`, `)`, `->`) is dropped silently.
            break
        }
    }
    return result
}

/// Lowercase the first character only — `B` → `b`, `TaskRepository` →
/// `taskRepository`, `DynamoDBTaskRepository` → `dynamoDBTaskRepository`.
/// The simplest convention that produces unambiguous, distinct names.
/// More sophisticated acronym-aware casing (`URLSession` →
/// `urlSession`) can be added later if generated names look awkward
/// enough to bother with.
private func lowerCamelCased(_ name: String) -> String {
    guard let first = name.first else { return name }
    return first.lowercased() + name.dropFirst()
}
