// Emit `_WireKeyChecks.swift` — compile-time type assertions that unify each
// keyed binding's `BindingKey<T>` against the consuming type.

/// Render the `_WireKeyChecks.swift` source the build plugin writes
/// alongside `_WireGraph.swift`. Contains one `_wireTypeCheck_*`
/// function per unique `(keyExpression, declaredType)` pair the
/// discovery found; inside each function, one `_check` call per
/// source-level usage of that pair, wrapped in `#sourceLocation`
/// directives so any compile failure is attributed back to the user's
/// source line.
///
/// The generic helper `_check<T>(_: BindingKey<T>, _: T.Type)` forces
/// Swift's type inference to unify `T` against both arguments. A
/// mismatch — `@Inject(Database.primary) var db: Cache` where
/// `Database.primary: BindingKey<Database>` — fails to compile because
/// no single `T` satisfies both. The compiler emits one error per
/// failing `_check` call, each attributed via `#sourceLocation` to the
/// originating user-source line.
///
/// Dedup: each `(keyExpression, declaredType)` pair gets one function.
/// All sites using the same pair are emitted as separate `_check`
/// calls inside that function. The success case (consistent
/// pair-usage) keeps the file size bounded; the failure case (the
/// pair mismatches) produces one Swift compile error per affected
/// site so the user can fix them all in one editing pass.
///
/// `any P` / `some P` existential property types are skipped — the
/// generic helper needs concrete `T` equality and existentials don't
/// satisfy it cleanly. Mismatches at those sites are still caught
/// later by the build plugin's missing-binding diagnostic at codegen.
///
/// The file is emitted even when there are no keyed bindings (just a
/// header comment) so SPM's declared-output-file contract holds
/// without conditional logic in the plugin.
package func renderWireKeyChecks(
    imports: [String],
    allBindings: [DiscoveredBinding],
    multibindingKeyReferences: Set<String> = []
) -> String {
    var lines: [String] = []

    lines.append("// Generated by WireGen — do not edit.")
    lines.append("//")
    lines.append("// Compile-time type assertions for keyed @Inject / @Provides")
    lines.append("// annotations. The functions below are never called; they")
    lines.append("// exist purely so the compiler unifies each key's `BindingKey<T>`")
    lines.append("// generic parameter with the consuming binding's type. A")
    lines.append("// mismatch surfaces as a Swift compile error attributed via")
    lines.append("// #sourceLocation to the user's source line.")

    let sortedImports = Array(Set(imports)).sorted()
    if !sortedImports.isEmpty {
        lines.append("")
        for line in sortedImports {
            lines.append(line)
        }
    }

    // Walk every binding, both keyed providers and keyed dependencies,
    // gathering (keyExpression, declaredType, location) for each.
    var groupedSites: [KeyCheckPair: [KeyCheckSite]] = [:]
    for site in collectKeyCheckSites(allBindings, excludingKeys: multibindingKeyReferences) {
        let pair = KeyCheckPair(key: site.keyExpression, type: site.declaredType)
        groupedSites[pair, default: []].append(site)
    }

    // Emit functions in deterministic (sorted) order — sort by type
    // first, then key — so the file is stable across runs.
    for (index, pair) in groupedSites.keys.sorted().enumerated() {
        let sites = (groupedSites[pair] ?? []).sorted { $0.location < $1.location }
        let functionName = "_wireTypeCheck_\(index + 1)"
        lines.append("")
        lines.append("private func \(functionName)() {")
        lines.append("    func _check<T>(_: BindingKey<T>, _: T.Type) {}")
        for site in sites {
            lines.append("")
            lines.append(
                "    #sourceLocation(file: \"\(site.location.file)\", line: \(site.location.line))"
            )
            lines.append("    _check(\(pair.key), \(pair.type).self)")
            lines.append("    #sourceLocation()")
        }
        lines.append("}")
    }

    lines.append("")
    return lines.joined(separator: "\n")
}

/// One source-level usage of a `(keyExpression, declaredType)` pair —
/// either a keyed `@Provides` site or a keyed `@Inject` site.
private struct KeyCheckSite {
    let keyExpression: String
    let declaredType: String
    let location: SourceLocation
}

/// Deduplication key for emitted check functions. Two sites with the
/// same `(key, type)` share a function; each contributes its own
/// `_check` call inside.
private struct KeyCheckPair: Hashable, Comparable {
    let key: String
    let type: String

    static func < (lhs: Self, rhs: Self) -> Bool {
        if lhs.type != rhs.type { return lhs.type < rhs.type }
        return lhs.key < rhs.key
    }
}

/// Walk every binding and pull out the keyed sites we need to check.
/// Two sources: the binding side (a keyed `@Provides` claims a slot
/// `(type, key)`) and the consumer side (each keyed dependency
/// requests a slot `(type, key)`). Both must type-check against the
/// same key declaration; both contribute sites.
private func collectKeyCheckSites(
    _ bindings: [DiscoveredBinding],
    excludingKeys multibindingKeyReferences: Set<String>
) -> [KeyCheckSite] {
    var sites: [KeyCheckSite] = []
    for binding in bindings {
        if case .provider(let provider) = binding,
            let key = provider.keyIdentifier,
            !multibindingKeyReferences.contains(key),
            shouldEmitCheck(forType: provider.boundType)
        {
            sites.append(
                KeyCheckSite(
                    keyExpression: key,
                    declaredType: provider.boundType,
                    location: provider.location
                )
            )
        }
        for dependency in binding.dependencies {
            guard let key = dependency.keyIdentifier else { continue }
            guard !multibindingKeyReferences.contains(key) else { continue }
            guard shouldEmitCheck(forType: dependency.type) else { continue }
            sites.append(
                KeyCheckSite(
                    keyExpression: key,
                    declaredType: dependency.type,
                    location: dependency.location
                )
            )
        }
    }
    return sites
}

/// `any P` / `some P` existential types break the generic helper's
/// `T == T` unification — `BindingKey<P>` (concrete) and `(any P).Type`
/// don't share a `T`. We skip these and rely on the build plugin's
/// missing-binding diagnostic to catch real mismatches at codegen.
/// Documented limitation; revisit if existential-typed bindings become
/// common enough that the loss of compile-time coverage hurts.
private func shouldEmitCheck(forType type: String) -> Bool {
    !type.hasPrefix("any ") && !type.hasPrefix("some ")
}
